import { useNavigate } from "react-router-dom";
import { ArrowRight, AlertTriangle, ChevronRight } from "lucide-react";
const C={paper:"var(--paper)",green:"var(--green)",greenDk:"var(--green-dk)",soil:"var(--soil)",amber:"var(--amber)",red:"var(--red)",line:"var(--line)",muted:"var(--muted)",cream:"var(--cream)"};
const D={supply:90,demand:64,matched:71,confirmed:[{buyer:"Nayans",crop:"Eggplant",kg:40,when:"Wed"},{buyer:"Market",crop:"Tomato",kg:24,when:"Fri"}],unmatched:[{kg:26,crop:"Tomato",date:"Sat"}]};
export default function DemandPipeline(){const nav=useNavigate();return(
<section className="rounded-2xl px-4 py-4" style={{background:C.paper,border:`1px solid ${C.line}`}}>
<div className="flex items-center justify-between mb-3"><div className="flex items-center gap-2"><ArrowRight size={15} style={{color:C.greenDk}}/><h3 className="text-sm font-semibold" style={{color:C.soil}}>Demand pipeline (this week)</h3></div><button onClick={()=>nav("/farm/buyers")} className="text-xs flex items-center gap-1" style={{color:C.greenDk}}>Open Buyers<ChevronRight size={12}/></button></div>
<div className="flex items-center gap-4 flex-wrap mb-2"><div className="text-center"><div style={{fontSize:20,fontWeight:800,color:C.soil}}>{D.supply}kg</div><div className="text-[11px]" style={{color:C.muted}}>supply ready</div></div><ArrowRight size={14} style={{color:C.muted}}/><div className="text-center"><div style={{fontSize:20,fontWeight:800,color:C.soil}}>{D.demand}kg</div><div className="text-[11px]" style={{color:C.muted}}>confirmed demand</div></div><div className="text-center ml-auto"><div style={{fontSize:20,fontWeight:800,color:C.greenDk}}>{D.matched}%</div><div className="text-[11px]" style={{color:C.muted}}>matched</div></div></div>
{D.unmatched.map((u,i)=>(<div key={i} className="flex items-center gap-1.5 text-[11px] px-2 py-1.5 rounded mb-2" style={{background:C.cream,color:C.amber}}><AlertTriangle size={11}/>{u.kg}kg {u.crop} on {u.date} with no buyer</div>))}
<div className="flex flex-col gap-1">{D.confirmed.map((c,i)=>(<div key={i} className="flex items-center gap-3 text-[12px] py-1" style={{borderBottom:`1px solid ${C.line}`}}><span className="font-semibold" style={{color:C.soil,minWidth:70}}>{c.buyer}</span><span style={{color:C.muted}}>{c.crop}</span><span style={{color:C.soil}}>{c.kg}kg</span><span className="ml-auto" style={{color:C.muted}}>{c.when}</span></div>))}</div></section>);}
