"""Seed missing rows into shared.productions to reach full 94-entry catalog.

Revision ID: 027_seed_productions_catalog
Revises: 026_one_active_cycle_per_pu
Create Date: 2026-04-22

Seeds the full 94-entry TFOS production catalog from TFOS_Foundation_v3_Complete.xlsx
(Productions sheet, 94 data rows) into shared.productions.

Idempotent: ON CONFLICT (production_id) DO NOTHING — existing rows are untouched.
Only the ~45 missing entries are inserted. Re-running is a no-op.

Catalog breakdown:
  CRP- 60 entries (crops + cash crops + vegetables)
  FRT- 16 entries (fruits)
  LIV-  9 entries (livestock 5, poultry 3, apiculture 1)
  FOR-  5 entries (forestry timber)
  AQU-  2 entries (aquaculture — rules 024-026 inactive per Part 6)
  SUP-  2 entries (support/feed crops)

Mapping from v3 Productions sheet (39 cols) to shared.productions (13 cols):
  production_id         -> production_id (PK)
  production_name       -> production_name
  local_name            -> local_name ('--' -> NULL)
  category              -> category
  family                -> plant_family
  lifecycle             -> lifecycle
  lifecycle starts "Perennial" -> is_perennial
  category in (Livestock, Poultry, Apiculture) -> is_livestock
  category = Forestry   -> is_forestry
  category = Aquaculture -> is_aquaculture
  status = Active       -> is_active_in_system
  sub_category|system_role|tier|farms|season|rotation_mode|notes -> notes (pipe-joined)

Metadata NOT persisted (not in deployed schema): varieties, best_months,
days_to_first_harvest, production_cycle_days, yield_low/avg/high, yield_unit,
units_per_acre, yield_per_acre_avg, price_fresh_fjd, price_processed_fjd,
revenue_per_acre_avg, risk_level, labor_intensity, capital_intensity,
harvest_type, yield_driver_stage, irrigation_class, nutrition_class,
maintenance_class, scalability_score, market_demand.

Phase 5 KB work can join these from a dedicated production_metadata table
if/when needed. For Phase 4, only the 13 columns here are required for
rotation gate, cycle creation, and farm_applicability resolution.
"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "027_seed_productions_catalog"
down_revision = "026_one_active_cycle_per_pu"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute(
        """
        INSERT INTO shared.productions (
            production_id, production_name, local_name, category,
            plant_family, lifecycle,
            is_perennial, is_livestock, is_forestry, is_aquaculture,
            is_active_in_system, notes
        ) VALUES
    ('AQU-PRW', 'Prawn Farm', 'Ura', 'Aquaculture', 'Penaeidae', 'Batch', false, false, false, true, true, 'sub_category=Crustacean | system_role=EXPORT_ENGINE | tier=Cashflow | farms=F001 | primary_season=Wet | rotation_mode=PondCycle | notes=High-value but technically unforgiving; export-quality handling matters.'),
    ('AQU-TIL', 'Tilapia Farm', 'Maleya', 'Aquaculture', 'Cichlidae', 'Batch', false, false, false, true, true, 'sub_category=Freshwater Fish | system_role=PROTEIN_ENGINE | tier=Cashflow | farms=F001 | primary_season=All | rotation_mode=PondCycle | notes=Water quality and feed conversion drive returns.'),
    ('CRP-AMR', 'Amaranthus', NULL, 'Crop', 'Amaranthaceae', 'Annual', false, false, false, false, true, 'sub_category=Leafy Crop | system_role=LEAF_ENGINE | tier=Support | farms=F001 + F002 | primary_season=All | rotation_mode=AnnualRotation | notes=Local leafy vegetable; excellent low-restriction break crop for all families.'),
    ('CRP-CAB', 'Cabbage', 'Kaveji', 'Crop', 'Brassicaceae', 'Annual', false, false, false, false, true, 'sub_category=Field Crop | system_role=CASHFLOW_ENGINE | tier=Support | farms=F001 | primary_season=Cool | rotation_mode=AnnualRotation | notes=Best in cooler window; splitting risk rises with erratic irrigation.'),
    ('CRP-CAP', 'Capsicum', 'Bell Pepper', 'Crop', 'Solanaceae', 'Annual', false, false, false, false, true, 'sub_category=Field Crop | system_role=CASHFLOW_ENGINE | tier=Cashflow | farms=F001 | primary_season=Dry | rotation_mode=AnnualRotation | notes=Premium but highly sensitive to thrips, virus and BER from irrigation inconsistency.'),
    ('CRP-CAR', 'Carrot', NULL, 'Crop', 'Apiaceae', 'Annual', false, false, false, false, true, 'sub_category=Root Crop | system_role=CASHFLOW_ENGINE | tier=Cashflow | farms=F001 | primary_season=Dry | rotation_mode=AnnualRotation | notes=Apiaceae root crop; AVOID after carrot/coriander/parsley; 60-day rest.'),
    ('CRP-CAS', 'Cassava', 'Tavioka', 'Crop', 'Euphorbiaceae', 'Annual', false, false, false, false, true, 'sub_category=Root Crop | system_role=STAPLE_ENGINE | tier=Stability | farms=F001 + F002 | primary_season=Wet | rotation_mode=AnnualRotation | notes=Never harvest without market plan; post-harvest deterioration is rapid.'),
    ('CRP-CAU', 'Cauliflower', NULL, 'Crop', 'Brassicaceae', 'Annual', false, false, false, false, true, 'sub_category=Field Crop | system_role=CASHFLOW_ENGINE | tier=Support | farms=F001 | primary_season=Cool | rotation_mode=AnnualRotation | notes=Brassica family; needs cooler conditions; shares clubroot risk with cabbage.'),
    ('CRP-CCB', 'Chinese Cabbage', 'Pak Choy', 'Crop', 'Brassicaceae', 'Annual', false, false, false, false, true, 'sub_category=Field Crop | system_role=CASHFLOW_ENGINE | tier=Support | farms=F001 | primary_season=All | rotation_mode=AnnualRotation | notes=Pak choy, wong bok; fast-cycle brassica; good year-round market.'),
    ('CRP-CDM', 'Cardamom', NULL, 'Crop', 'Zingiberaceae', 'Perennial', true, false, false, false, true, 'sub_category=Spice / Cash Crop | system_role=SPECIALTY_ENGINE | tier=Wealth | farms=F002 | primary_season=Dry | rotation_mode=AgroforestryOrPostHarvestRotation | notes=Undercanopy spice; shade-tolerant; Zingiberaceae family; 60-day family rest.'),
    ('CRP-CHI', 'Chillies', 'Rokete', 'Crop', 'Solanaceae', 'Annual', false, false, false, false, true, 'sub_category=Field Crop | system_role=CASHFLOW_ENGINE | tier=Cashflow | farms=F001 | primary_season=Dry | rotation_mode=AnnualRotation | notes=High-value volatile crop; thrips, mites, viruses determine profitability.'),
    ('CRP-COA', 'Cocoa', 'Kokoroa', 'Cash Crop', 'Malvaceae', 'Perennial tree', true, false, false, false, true, 'sub_category=Tree Crop | system_role=Cash Crop | tier=Standard | farms=Wet zone (Taveuni, Viti Levu highlands) | primary_season=Wet season | rotation_mode=Permanent | notes=Fiji Cacao & Chocolate Co buys wet beans. Fermentation and drying adds value. Intercrop with banana/coconut for shade. Pod borer and black pod are main risks.'),
    ('CRP-COF', 'Coffee', 'Kofi', 'Cash Crop', 'Rubiaceae', 'Perennial', true, false, false, false, true, 'sub_category=Tree Crop | system_role=Cash Crop | tier=Standard | farms=Highland farms (>400m altitude) | primary_season=Dry/cool | rotation_mode=Permanent | notes=Highland crop: Taveuni, Namosi, Ba highlands. Arabica quality. Coffee rust (Hemileia) is main threat. Small Fiji specialty market growing.'),
    ('CRP-COR', 'Coriander', NULL, 'Crop', 'Apiaceae', 'Annual', false, false, false, false, true, 'sub_category=Herb | system_role=HERB_ENGINE | tier=Support | farms=F001 | primary_season=All | rotation_mode=AnnualRotation | notes=Fast-cycle herb; Apiaceae family; AVOID after carrot/parsley; 60-day rest.'),
    ('CRP-CUC', 'Cucumber', 'Kuikaba', 'Crop', 'Cucurbitaceae', 'Annual', false, false, false, false, true, 'sub_category=Field Crop | system_role=CASHFLOW_ENGINE | tier=Cashflow | farms=F001 | primary_season=Dry | rotation_mode=AnnualRotation | notes=Fast turnover crop; regular picking and disease control are non-negotiable.'),
    ('CRP-CUL', 'Curry Leaves', NULL, 'Crop', 'Rutaceae', 'Perennial', true, false, false, false, true, 'sub_category=Herb | system_role=HERB_ENGINE | tier=Support | farms=F001 | primary_season=All | rotation_mode=PermanentOrReblock | notes=Small perennial Rutaceae tree/shrub; harvest leaves continuously.'),
    ('CRP-CWP', 'Cowpea', NULL, 'Crop', 'Fabaceae', 'Annual', false, false, false, false, true, 'sub_category=Legume | system_role=SOIL_ENGINE | tier=Support | farms=F001 + F002 | primary_season=Wet | rotation_mode=AnnualRotation | notes=Drought-tolerant nitrogen-fixing legume; excellent break crop and cover.'),
    ('CRP-DAL', 'Dalo (Taro)', 'Dalo', 'Crop', 'Araceae', 'Perennial', true, false, false, false, true, 'sub_category=Root Crop | system_role=STAPLE_ENGINE | tier=Stability | farms=F001 + F002 | primary_season=Wet | rotation_mode=AnnualRotation | notes=Wetland taro requires steady moisture and leaf blight vigilance.'),
    ('CRP-DTN', 'Dalo ni Tana', 'Dalo ni Tana', 'Crop', 'Araceae', 'Annual', false, false, false, false, true, 'sub_category=Root Crop | system_role=STAPLE_ENGINE | tier=Stability | farms=F001 + F002 | primary_season=Wet | rotation_mode=AnnualRotation | notes=Dryland taro offers flexibility but still needs weed and moisture discipline.'),
    ('CRP-DUR', 'Duruka', 'Duruka', 'Crop', 'Poaceae', 'Perennial', true, false, false, false, true, 'sub_category=Local Specialty | system_role=SPECIALTY_ENGINE | tier=Support | farms=F001 + F002 | primary_season=Wet | rotation_mode=ReblockAfterDecline | notes=High-value local seasonal crop with strong cultural demand.'),
    ('CRP-EGG', 'Eggplant', 'Baigani', 'Crop', 'Solanaceae', 'Annual', false, false, false, false, true, 'sub_category=Field Crop | system_role=CASHFLOW_ENGINE | tier=Cashflow | farms=F001 + F002 | primary_season=Dry | rotation_mode=AnnualRotation | notes=Most stable commercial solanaceae crop under Fiji field conditions.'),
    ('CRP-FRB', 'French Beans', 'Bean', 'Crop', 'Fabaceae', 'Annual', false, false, false, false, true, 'sub_category=Field Crop | system_role=SOIL_ENGINE | tier=Support | farms=F001 | primary_season=Dry | rotation_mode=AnnualRotation | notes=Good rotation crop; keep N modest to preserve nodulation.'),
    ('CRP-GAR', 'Garlic', NULL, 'Crop', 'Amaryllidaceae', 'Annual', false, false, false, false, true, 'sub_category=Field Crop | system_role=CASHFLOW_ENGINE | tier=Cashflow | farms=F001 | primary_season=Dry | rotation_mode=AnnualRotation | notes=Allium; allelopathic; high per-kg value; AVOID after onion/spring onion.'),
    ('CRP-GIN', 'Ginger', 'Ginger', 'Crop', 'Zingiberaceae', 'Annual', false, false, false, false, true, 'sub_category=Spice Crop | system_role=CASHFLOW_ENGINE | tier=Cashflow | farms=F001 | primary_season=Dry | rotation_mode=AnnualRotation | notes=Seed quality, drainage and disease control matter more than brute fertilizer.'),
    ('CRP-GOU', 'Gourd', NULL, 'Crop', 'Cucurbitaceae', 'Annual', false, false, false, false, true, 'sub_category=Field Crop | system_role=FIELD_ENGINE | tier=Support | farms=F001 | primary_season=Dry | rotation_mode=AnnualRotation | notes=Cucurbit family; AVOID after watermelon/cucumber/squash; 90-day rest.'),
    ('CRP-HRB', 'Herbs (General)', NULL, 'Crop', 'Various', 'Annual', false, false, false, false, true, 'sub_category=Herb | system_role=HERB_ENGINE | tier=Support | farms=F001 | primary_season=All | rotation_mode=AnnualRotation | notes=Mixed herb block; very low rotation restrictions.'),
    ('CRP-KAV', 'Kava', 'Yaqona', 'Crop', 'Piperaceae', 'Perennial', true, false, false, false, true, 'sub_category=Cash Crop | system_role=LONG_TERM_ENGINE | tier=Wealth | farms=F001 | primary_season=Dry | rotation_mode=AgroforestryOrPostHarvestRotation | notes=Value depends on age, genetics, shade, drainage and chemical quality.'),
    ('CRP-KAW', 'Kawai / Jicama', NULL, 'Crop', 'Fabaceae', 'Annual', false, false, false, false, true, 'sub_category=Root Crop | system_role=CASHFLOW_ENGINE | tier=Support | farms=F001 | primary_season=Wet | rotation_mode=AnnualRotation | notes=Root legume; N-fixing root crop; limited but growing market.'),
    ('CRP-LAB', 'Lablab Bean', NULL, 'Crop', 'Fabaceae', 'Annual', false, false, false, false, true, 'sub_category=Legume | system_role=SOIL_ENGINE | tier=Support | farms=F001 + F002 | primary_season=Wet | rotation_mode=AnnualRotation | notes=Dual-purpose N-fixer; cover crop and food legume; heavy N loads.'),
    ('CRP-LBN', 'Long Bean', NULL, 'Crop', 'Fabaceae', 'Annual', false, false, false, false, true, 'sub_category=Field Crop | system_role=CASHFLOW_ENGINE | tier=Cashflow | farms=F001 | primary_season=Dry | rotation_mode=AnnualRotation | notes=Fast-cycle cash crop; highly sensitive to aphids and pod borers; requires trellis.'),
    ('CRP-LET', 'Lettuce', NULL, 'Crop', 'Asteraceae', 'Annual', false, false, false, false, true, 'sub_category=Field Crop | system_role=CASHFLOW_ENGINE | tier=Support | farms=F001 | primary_season=All | rotation_mode=AnnualRotation | notes=Fast-cycle leafy; low rotation restriction; excellent break crop.'),
    ('CRP-MAZ', 'Maize / Corn', NULL, 'Crop', 'Poaceae', 'Annual', false, false, false, false, true, 'sub_category=Field Crop | system_role=STAPLE_ENGINE | tier=Stability | farms=F001 + F002 | primary_season=Wet | rotation_mode=AnnualRotation | notes=Field grain corn for fodder and staple; different from sweet corn in market use.'),
    ('CRP-MIN', 'Mint', NULL, 'Crop', 'Lamiaceae', 'Perennial', true, false, false, false, true, 'sub_category=Herb | system_role=HERB_ENGINE | tier=Support | farms=F001 | primary_season=All | rotation_mode=ReblockAfterDecline | notes=Perennial spreading herb; low rotation restriction; good ground cover.'),
    ('CRP-MNB', 'Mung Bean', NULL, 'Crop', 'Fabaceae', 'Annual', false, false, false, false, true, 'sub_category=Legume | system_role=SOIL_ENGINE | tier=Support | farms=F001 | primary_season=All | rotation_mode=AnnualRotation | notes=Fast-cycle N-fixer; excellent rotation crop before heavy feeders.'),
    ('CRP-MOR', 'Drumstick / Moringa', NULL, 'Crop', 'Moringaceae', 'Perennial', true, false, false, false, true, 'sub_category=Vegetable/Tree | system_role=SPECIALTY_ENGINE | tier=Support | farms=F001 + F002 | primary_season=All | rotation_mode=PermanentAgroforestry | notes=Multi-purpose tree; leaves and pods harvested; minimal rotation restriction.'),
    ('CRP-OKR', 'Okra', NULL, 'Crop', 'Malvaceae', 'Annual', false, false, false, false, true, 'sub_category=Field Crop | system_role=CASHFLOW_ENGINE | tier=Support | farms=F001 | primary_season=All | rotation_mode=AnnualRotation | notes=Tropical vegetable; heat tolerant; AVOID after other Malvaceae; 60-day rest.'),
    ('CRP-ONI', 'Onion', NULL, 'Crop', 'Amaryllidaceae', 'Annual', false, false, false, false, true, 'sub_category=Field Crop | system_role=CASHFLOW_ENGINE | tier=Cashflow | farms=F001 | primary_season=Dry | rotation_mode=AnnualRotation | notes=Allium family; AVOID after other Alliums; 90-day minimum rest.'),
    ('CRP-OTA', 'Ota (Fern)', NULL, 'Crop', 'Pteridophyte', 'Perennial', true, false, false, false, true, 'sub_category=Leafy Crop | system_role=LEAF_ENGINE | tier=Support | farms=F002 | primary_season=Wet | rotation_mode=ReblockAfterDecline | notes=Shade-loving specialty crop; quality drops fast in dry exposure.'),
    ('CRP-PAR', 'Parsley', NULL, 'Crop', 'Apiaceae', 'Annual', false, false, false, false, true, 'sub_category=Herb | system_role=HERB_ENGINE | tier=Support | farms=F001 | primary_season=All | rotation_mode=AnnualRotation | notes=Herb; Apiaceae family; AVOID after carrot/coriander; 60-day rest.'),
    ('CRP-PGP', 'Pigeon Pea', NULL, 'Crop', 'Fabaceae', 'Annual', false, false, false, false, true, 'sub_category=Legume | system_role=SOIL_ENGINE | tier=Support | farms=F001 + F002 | primary_season=Wet | rotation_mode=AnnualRotation | notes=Long-cycle woody N-fixer; food and fodder use; perennial in some systems.'),
    ('CRP-PNT', 'Peanut', NULL, 'Crop', 'Fabaceae', 'Annual', false, false, false, false, true, 'sub_category=Legume | system_role=CASHFLOW_ENGINE | tier=Cashflow | farms=F001 | primary_season=Wet | rotation_mode=AnnualRotation | notes=Underground legume; aflatoxin risk post-harvest; high per-kg value if dried well.'),
    ('CRP-POT', 'Potato', NULL, 'Crop', 'Solanaceae', 'Annual', false, false, false, false, true, 'sub_category=Root Crop | system_role=CASHFLOW_ENGINE | tier=Cashflow | farms=F001 | primary_season=Dry | rotation_mode=AnnualRotation | notes=Same Solanaceae family as tomato. AVOID after solanaceae block. 60-day minimum rest.'),
    ('CRP-RAD', 'Radish', NULL, 'Crop', 'Brassicaceae', 'Annual', false, false, false, false, true, 'sub_category=Root Crop | system_role=FIELD_ENGINE | tier=Support | farms=F001 | primary_season=All | rotation_mode=AnnualRotation | notes=Fast-cycle break crop; brassica family restriction applies.'),
    ('CRP-RDR', 'Rice (Dryland)', NULL, 'Crop', 'Poaceae', 'Annual', false, false, false, false, true, 'sub_category=Field Crop | system_role=STAPLE_ENGINE | tier=Stability | farms=F001 + F002 | primary_season=Wet | rotation_mode=AnnualRotation | notes=Upland rice; Pacific staple grain; lower yield than wetland.'),
    ('CRP-ROU', 'Rourou / Bele', NULL, 'Crop', 'Amaranthaceae', 'Perennial', true, false, false, false, true, 'sub_category=Leafy Crop | system_role=LEAF_ENGINE | tier=Support | farms=F001 + F002 | primary_season=All | rotation_mode=ReblockAfterDecline | notes=Continuous leafy crop; frequent clean harvest drives value.'),
    ('CRP-RWT', 'Rice (Wetland)', NULL, 'Crop', 'Poaceae', 'Annual', false, false, false, false, true, 'sub_category=Field Crop | system_role=STAPLE_ENGINE | tier=Stability | farms=F001 + F002 | primary_season=Wet | rotation_mode=AnnualRotation | notes=Paddy rice; flooded system; drain soil before next rotation; rehab required.'),
    ('CRP-SCN', 'Sweet Corn', 'Sila', 'Crop', 'Poaceae', 'Annual', false, false, false, false, true, 'sub_category=Field Crop | system_role=CASHFLOW_ENGINE | tier=Support | farms=F001 | primary_season=Dry | rotation_mode=AnnualRotation | notes=Yield depends heavily on stand uniformity and pollination.'),
    ('CRP-SON', 'Spring Onion', NULL, 'Crop', 'Amaryllidaceae', 'Annual', false, false, false, false, true, 'sub_category=Field Crop | system_role=CASHFLOW_ENGINE | tier=Support | farms=F001 | primary_season=All | rotation_mode=AnnualRotation | notes=Fast-cycle allium; AVOID after garlic/onion block; 90-day rest.'),
    ('CRP-SOR', 'Sorghum', NULL, 'Crop', 'Poaceae', 'Annual', false, false, false, false, true, 'sub_category=Field Crop | system_role=FODDER_ENGINE | tier=Stability | farms=F001 + F002 | primary_season=Wet | rotation_mode=AnnualRotation | notes=Drought-tolerant grain and fodder; 90-day rest before re-planting grass family.'),
    ('CRP-SPT', 'Sweet Potato', 'Kumala', 'Crop', 'Convolvulaceae', 'Annual', false, false, false, false, true, 'sub_category=Root Crop | system_role=STAPLE_ENGINE | tier=Stability | farms=F001 + F002 | primary_season=Wet | rotation_mode=AnnualRotation | notes=Strong staple; root initiation in first 2-4 weeks determines yield.'),
    ('CRP-SQU', 'Squash / Pumpkin', 'Papukeni', 'Crop', 'Cucurbitaceae', 'Annual', false, false, false, false, true, 'sub_category=Field Crop | system_role=FIELD_ENGINE | tier=Support | farms=F001 | primary_season=Dry | rotation_mode=AnnualRotation | notes=Space-demanding vine crop; more forgiving than watermelon.'),
    ('CRP-SUG', 'Sugarcane', 'Dovu', 'Crop', 'Poaceae', 'Perennial', true, false, false, false, true, 'sub_category=Cash Crop | system_role=BULK_ENGINE | tier=Support | farms=F001 | primary_season=Wet | rotation_mode=ReblockAfterHarvest | notes=Commercial value depends on logistics, sucrose and mill access.'),
    ('CRP-TOM', 'Tomato', 'Tomata', 'Crop', 'Solanaceae', 'Annual', false, false, false, false, true, 'sub_category=Field Crop | system_role=CASHFLOW_ENGINE | tier=Cashflow | farms=F001 | primary_season=Dry | rotation_mode=AnnualRotation | notes=High-management crop; rain and blight pressure can wipe out margins.'),
    ('CRP-TUR', 'Turmeric', NULL, 'Crop', 'Zingiberaceae', 'Annual', false, false, false, false, true, 'sub_category=Spice Crop | system_role=CASHFLOW_ENGINE | tier=Support | farms=F001 + F002 | primary_season=Wet | rotation_mode=AnnualRotation | notes=Strong dried/processed upside if curing is done properly.'),
    ('CRP-URB', 'Urd Bean', NULL, 'Crop', 'Fabaceae', 'Annual', false, false, false, false, true, 'sub_category=Legume | system_role=SOIL_ENGINE | tier=Support | farms=F001 | primary_season=Wet | rotation_mode=AnnualRotation | notes=Black gram; fast-cycle N-fixer; AVOID after French bean/long bean; 60-day rest.'),
    ('CRP-URO', 'Uronivonu (Bele/Fiji Spinach)', 'Uronivonu / Bele', 'Vegetable', 'Malvaceae', 'Perennial', true, false, false, false, true, 'sub_category=Traditional Leafy Green | system_role=Subsistence/Market | tier=Beginner | farms=All farms (subsistence and market) | primary_season=Year-round | rotation_mode=Permanent rotation | notes=Traditional Fiji leafy green (Abelmoschus manihot type). Cuttings every 2-3 weeks. Extremely hardy. High vitamin/mineral content. Integral to traditional Fijian diet.'),
    ('CRP-VAN', 'Vanilla', 'Vanila', 'Cash Crop', 'Orchidaceae', 'Perennial vine', true, false, false, false, true, 'sub_category=Spice Vine | system_role=Cash Crop | tier=Advanced | farms=All farms (sheltered/shaded sites) | primary_season=Dry/early wet | rotation_mode=Long-cycle | notes=Year 1-3 establishment = zero revenue. Hand pollination 100% required. Requires shade/support tree. FJD 80-200/kg cured beans farm gate. Export market significant.'),
    ('CRP-WAT', 'Watermelon', 'Meleni', 'Crop', 'Cucurbitaceae', 'Annual', false, false, false, false, true, 'sub_category=Field Crop | system_role=CASHFLOW_ENGINE | tier=Cashflow | farms=F001 | primary_season=Dry | rotation_mode=AnnualRotation | notes=Seasonal dry-season cash crop; wet-season planting without protection is high risk.'),
    ('CRP-WCR', 'Watercress', NULL, 'Crop', 'Brassicaceae', 'Annual', false, false, false, false, true, 'sub_category=Leafy Crop | system_role=LEAF_ENGINE | tier=Support | farms=F002 | primary_season=Wet | rotation_mode=AnnualRotation | notes=Brassicaceae water vegetable; limited to wet/irrigated zones.'),
    ('CRP-WNB', 'Winged Bean', NULL, 'Crop', 'Fabaceae', 'Annual', false, false, false, false, true, 'sub_category=Legume | system_role=SOIL_ENGINE | tier=Support | farms=F001 + F002 | primary_season=Wet | rotation_mode=AnnualRotation | notes=High-protein tropical legume; all plant parts edible; strong soil N benefit.'),
    ('CRP-YAM', 'Yam', 'Uvi', 'Crop', 'Dioscoreaceae', 'Annual', false, false, false, false, true, 'sub_category=Root Crop | system_role=STAPLE_ENGINE | tier=Stability | farms=F002 | primary_season=Wet | rotation_mode=AnnualRotation | notes=High labor crop; staking quality strongly affects output.'),
    ('CRP-ZUC', 'Zucchini', NULL, 'Crop', 'Cucurbitaceae', 'Annual', false, false, false, false, true, 'sub_category=Field Crop | system_role=CASHFLOW_ENGINE | tier=Support | farms=F001 | primary_season=Dry | rotation_mode=AnnualRotation | notes=Cucurbit family; AVOID after watermelon/cucumber/squash; 90-day rest.'),
    ('FOR-AGA', 'Agarwood', 'Alpasita', 'Forestry', 'Thymelaeaceae', 'Perennial', true, false, true, false, true, 'sub_category=Resin Timber | system_role=LONG_TERM_ENGINE | tier=Wealth | farms=F002 | primary_season=Wet | rotation_mode=PermanentForestry | notes=Inoculation timing and resin formation determine value more than growth alone.'),
    ('FOR-MAH', 'Mahogany', NULL, 'Forestry', 'Meliaceae', 'Perennial', true, false, true, false, true, 'sub_category=Timber | system_role=TIMBER_ENGINE | tier=Wealth | farms=F002 | primary_season=Wet | rotation_mode=PermanentForestry | notes=Shoot borer and trunk form matter more than simple survival.'),
    ('FOR-PIN', 'Pine', 'Paini', 'Forestry', 'Pinaceae', 'Perennial', true, false, true, false, true, 'sub_category=Timber | system_role=TIMBER_ENGINE | tier=Wealth | farms=F002 | primary_season=Wet | rotation_mode=PermanentForestry | notes=Industrial timber with long rotation and low management after establishment.'),
    ('FOR-SAN', 'Sandalwood', 'Yasi', 'Forestry', 'Santalaceae', 'Perennial', true, false, true, false, true, 'sub_category=Fragrant Timber | system_role=LONG_TERM_ENGINE | tier=Wealth | farms=F002 | primary_season=Wet | rotation_mode=PermanentForestry | notes=Host management and heartwood/oil formation are decisive.'),
    ('FOR-TEK', 'Teak', NULL, 'Forestry', 'Lamiaceae', 'Perennial', true, false, true, false, true, 'sub_category=Timber | system_role=TIMBER_ENGINE | tier=Wealth | farms=F002 | primary_season=Wet | rotation_mode=PermanentForestry | notes=Timber value depends on spacing, form and rotation discipline.'),
    ('FRT-AVO', 'Avocado', NULL, 'Fruit', 'Lauraceae', 'Perennial', true, false, false, false, true, 'sub_category=Fruit Crop | system_role=FOOD_ENGINE | tier=Support | farms=F001 + F002 | primary_season=Wet | rotation_mode=PermanentAgroforestry | notes=Long-gestation orchard; drainage, root health, wind protection matter most.'),
    ('FRT-BAN', 'Banana / Vudi', 'Vudi', 'Fruit', 'Musaceae', 'Perennial', true, false, false, false, true, 'sub_category=Fruit Crop | system_role=FOOD_ENGINE | tier=Cashflow | farms=F001 + F002 | primary_season=Wet | rotation_mode=ManagedRatoonOrReblock | notes=Ratoon-managed crop; wind and leaf disease are key constraints.'),
    ('FRT-BRF', 'Breadfruit', 'Uto', 'Fruit', 'Moraceae', 'Perennial', true, false, false, false, true, 'sub_category=Fruit Crop | system_role=TRADITIONAL_ENGINE | tier=Wealth | farms=F002 | primary_season=Wet | rotation_mode=PermanentAgroforestry | notes=Traditional long-term food tree; processed value can exceed fresh value.'),
    ('FRT-CIT', 'Citrus', NULL, 'Fruit', 'Rutaceae', 'Perennial', true, false, false, false, true, 'sub_category=Fruit Tree | system_role=FOOD_ENGINE | tier=Wealth | farms=F001 + F002 | primary_season=Wet | rotation_mode=PermanentAgroforestry | notes=Orange, mandarin, lemon, lime; citrus greening (HLB) is key long-term risk.'),
    ('FRT-CMQ', 'Cumquat', 'Moli', 'Fruit', 'Rutaceae', 'Perennial', true, false, false, false, true, 'sub_category=Fruit Crop | system_role=SPECIALTY_ENGINE | tier=Support | farms=F001 | primary_season=Wet | rotation_mode=PermanentAgroforestry | notes=Niche citrus; manageable tree size; specialty-market access required.'),
    ('FRT-COC', 'Coconut', 'Niu', 'Fruit', 'Arecaceae', 'Perennial', true, false, false, false, true, 'sub_category=Fruit Crop | system_role=EXPORT_ENGINE | tier=Wealth | farms=F002 | primary_season=Wet | rotation_mode=PermanentAgroforestry | notes=Long-cycle perennial with multiple value channels: nuts, copra, oil.'),
    ('FRT-DRG', 'Dragon Fruit', NULL, 'Fruit', 'Cactaceae', 'Perennial', true, false, false, false, true, 'sub_category=Fruit Crop | system_role=SPECIALTY_ENGINE | tier=Wealth | farms=F001 | primary_season=Wet | rotation_mode=PermanentOrReblock | notes=Needs trellis discipline and targeted market; not a lazy crop.'),
    ('FRT-GUA', 'Guava', 'Quwawa', 'Fruit', 'Myrtaceae', 'Perennial', true, false, false, false, true, 'sub_category=Fruit Crop | system_role=FOOD_ENGINE | tier=Support | farms=F001 + F002 | primary_season=Wet | rotation_mode=PermanentOrReblock | notes=Moderate-input fruit tree with fruit fly pressure risk.'),
    ('FRT-MAN', 'Mango', 'Mango / Madrai', 'Fruit', 'Anacardiaceae', 'Perennial', true, false, false, false, true, 'sub_category=Tropical Tree Fruit | system_role=Fruit | tier=Standard | farms=All farms | primary_season=Wet season (summer) | rotation_mode=Permanent | notes=Very common in Fiji. Seasonal glut Jan-Feb drops farm gate prices. Value-adding (jam/dried/pulp) doubles margins. Grafted trees produce year 2-3. Seedlings year 5-7.'),
    ('FRT-NON', 'Kura / Noni', NULL, 'Fruit', 'Rubiaceae', 'Perennial', true, false, false, false, true, 'sub_category=Fruit Tree | system_role=SPECIALTY_ENGINE | tier=Support | farms=F001 + F002 | primary_season=All | rotation_mode=PermanentAgroforestry | notes=Medicinal fruit tree; drought tolerant; niche health/export market.'),
    ('FRT-PAP', 'Papaya', 'Maoli', 'Fruit', 'Caricaceae', 'Perennial', true, false, false, false, true, 'sub_category=Fruit Crop | system_role=CASHFLOW_ENGINE | tier=Cashflow | farms=F001 | primary_season=Wet | rotation_mode=ReblockAfterDecline | notes=Fast-return fruit crop; virus and sex ratio management matter.'),
    ('FRT-PAS', 'Passionfruit', NULL, 'Fruit', 'Passifloraceae', 'Perennial', true, false, false, false, true, 'sub_category=Fruit Crop | system_role=CASHFLOW_ENGINE | tier=Wealth | farms=F001 | primary_season=All | rotation_mode=ReblockAfterDecline | notes=Vine fruit; Fusarium and woodiness virus are key risks; reblock after 3-4 years.'),
    ('FRT-PIN', 'Pineapple', 'Painapiu', 'Fruit', 'Bromeliaceae', 'Perennial', true, false, false, false, true, 'sub_category=Fruit Crop | system_role=CASHFLOW_ENGINE | tier=Cashflow | farms=F001 + F002 | primary_season=Wet | rotation_mode=ManagedRatoonOrReblock | notes=Density-sensitive crop; profitability depends on stand uniformity.'),
    ('FRT-PLN', 'Plantain', 'Vudi (cooking)', 'Fruit', 'Musaceae', 'Perennial', true, false, false, false, true, 'sub_category=Fruit Crop | system_role=FOOD_ENGINE | tier=Cashflow | farms=F001 + F002 | primary_season=Wet | rotation_mode=ManagedRatoonOrReblock | notes=Cooking banana; managed ratoon system; wind and Sigatoka as for dessert banana.'),
    ('FRT-RME', 'Rockmelon / Cantaloupe', NULL, 'Fruit', 'Cucurbitaceae', 'Annual', false, false, false, false, true, 'sub_category=Fruit Crop | system_role=CASHFLOW_ENGINE | tier=Cashflow | farms=F001 | primary_season=Dry | rotation_mode=AnnualRotation | notes=High-value cucurbit melon; AVOID after watermelon/cucumber; 90-day rest.'),
    ('FRT-SRS', 'Soursop', NULL, 'Fruit', 'Annonaceae', 'Perennial', true, false, false, false, true, 'sub_category=Fruit Tree | system_role=FOOD_ENGINE | tier=Support | farms=F001 + F002 | primary_season=Wet | rotation_mode=PermanentAgroforestry | notes=Permanent fruit tree; drought tolerant once established.'),
    ('LIV-API', 'Apiculture (Honey + Pollination)', 'Oni', 'Apiculture', 'Apidae', 'Perennial', true, true, false, false, true, 'sub_category=Honey + Pollination | system_role=POLLINATION_ENGINE | tier=Support | farms=F001 + F002 | primary_season=All | rotation_mode=Overlay | notes=Dual-output: honey sales plus pollination support across crop blocks.'),
    ('LIV-CAT', 'Beef Cattle', 'Bulumakau', 'Livestock', 'Bovidae', 'Perennial', true, true, false, false, true, 'sub_category=Large Ruminant | system_role=LIVESTOCK_ENGINE | tier=Stability | farms=F002 | primary_season=All | rotation_mode=LivestockIntegration | notes=Land-heavy, slower-turnover livestock system.'),
    ('LIV-DCK', 'Duck', 'Pato', 'Poultry', 'Anatidae', 'Perennial', true, true, false, false, true, 'sub_category=Dual Purpose Bird | system_role=WET_SYSTEM_ENGINE | tier=Support | farms=F001 + F002 | primary_season=All | rotation_mode=LivestockIntegration | notes=More resilient in wet systems than chickens; market is smaller.'),
    ('LIV-DIR', 'Dairy Cattle', 'Bulumakau (sucu)', 'Livestock', 'Bovidae', 'Perennial', true, true, false, false, true, 'sub_category=Dairy | system_role=INCOME_ENGINE | tier=Stability | farms=F001 + F002 | primary_season=All | rotation_mode=LivestockIntegration | notes=Milk system depends on feed consistency, hygiene and breed performance.'),
    ('LIV-GOA', 'Goat', 'Me', 'Livestock', 'Bovidae', 'Perennial', true, true, false, false, true, 'sub_category=Small Ruminant | system_role=LIVESTOCK_ENGINE | tier=Stability | farms=F002 | primary_season=All | rotation_mode=LivestockIntegration | notes=Scalable small ruminant enterprise if grazing and health are controlled.'),
    ('LIV-PBR', 'Broiler Chicken', 'Toa', 'Poultry', 'Galliformes', 'Batch', false, true, false, false, true, 'sub_category=Meat Bird | system_role=FAST_CASHFLOW_ENGINE | tier=Cashflow | farms=F001 | primary_season=All | rotation_mode=LivestockIntegration | notes=Fastest turnover; margin is fragile to feed price and mortality.'),
    ('LIV-PIG', 'Pig', 'Vuaka', 'Livestock', 'Suidae', 'Perennial', true, true, false, false, true, 'sub_category=Swine | system_role=CASHFLOW_ENGINE | tier=Cashflow | farms=F001 + F002 | primary_season=All | rotation_mode=LivestockIntegration | notes=Strong cashflow but feed cost and biosecurity define margin.'),
    ('LIV-PLY', 'Layer Chicken', 'Toa (valutu yaloka)', 'Poultry', 'Galliformes', 'Perennial', true, true, false, false, true, 'sub_category=Egg Bird | system_role=INCOME_ENGINE | tier=Cashflow | farms=F001 | primary_season=All | rotation_mode=LivestockIntegration | notes=Stable cashflow if feed and mortality are tightly managed.'),
    ('LIV-SHP', 'Sheep (Meat)', 'Sipi', 'Livestock', 'Bovidae', 'Perennial', true, true, false, false, true, 'sub_category=Small Ruminant | system_role=Protein | tier=Standard | farms=Drier zones (Nadi, Sigatoka, Tailevu) | primary_season=Year-round | rotation_mode=Grazing rotation | notes=Limited sheep farming in Fiji. Barbados Blackbelly most tick/heat tolerant. Requires rotational grazing. Market demand low vs goat. Worm (nematode) resistance management critical.'),
    ('SUP-LEG', 'Legume Cover Crop', NULL, 'Support', 'Fabaceae', 'Annual', false, false, false, false, true, 'sub_category=Soil Improvement | system_role=SOIL_ENGINE | tier=Support | farms=F001 + F002 | primary_season=Wet | rotation_mode=AnnualRotation | notes=Internal soil-building engine; not a direct cash crop.'),
    ('SUP-NAP', 'Napier Grass', NULL, 'Support', 'Poaceae', 'Perennial', true, false, false, false, true, 'sub_category=Feed Crop | system_role=FEED_ENGINE | tier=Support | farms=F001 + F002 | primary_season=Wet | rotation_mode=ReblockAfterDecline | notes=Feed crop; value is internal through livestock conversion efficiency.')
        ON CONFLICT (production_id) DO NOTHING
        """
    )


def downgrade() -> None:
    # Irreversible seed. Rolling this migration back would require knowing
    # which rows were pre-existing vs inserted by this migration.
    # If a rollback is truly needed, manually DELETE the specific production_ids
    # that were added — do NOT wipe shared.productions wholesale.
    raise RuntimeError(
        "Migration 027 is a seed migration and cannot be auto-downgraded. "
        "Manually DELETE specific production_ids if rollback is required."
    )
