"""173 — Sponsored Farmer Seats (Product 5): orgs + redeemable seats

The highest-conviction Pacific channel: an organization (bank/ministry/NGO)
sponsors N farmer seats at FJD 10/seat/month; each seat is a redemption code a
farmer enters to receive the funded farmer plan free. Farmers = distribution,
the sponsor pays for the outcome.

Two global tables (community.* — no RLS, admin-writable):
  community.sponsor_orgs    — the sponsoring organisation + batch terms
  community.sponsored_seats — one row per seat/code, redemption state + a
                              denormalised farmer snapshot (avoids cross-tenant
                              RLS reads on the sponsor impact view)

Redemption flips the farmer's tenant.tenants.subscription_tier to the seat's
granted_tier (mirroring the admin approve flow), recording prev_tier +
prev_tis_daily_limit so a revoke restores the farmer exactly.

Additive/idempotent; reversible. Apply as owner (Strike #123).

Revision ID: 173_sponsored_seats
Revises: 172_monetization_products
"""
from alembic import op
import sqlalchemy as sa

revision = "173_sponsored_seats"
down_revision = "172_monetization_products"
branch_labels = None
depends_on = None


def upgrade():
    conn = op.get_bind()

    conn.execute(sa.text("""
        CREATE TABLE IF NOT EXISTS community.sponsor_orgs (
            id                 TEXT PRIMARY KEY,
            name               TEXT NOT NULL,
            kind               TEXT NOT NULL DEFAULT 'NGO'
                               CHECK (kind IN ('BANK','MINISTRY','NGO','COOP','CORPORATE','OTHER')),
            contact_name       TEXT,
            contact_email      TEXT,
            granted_tier       TEXT NOT NULL DEFAULT 'BASIC',   -- farmer plan code seats grant
            price_per_seat_fjd NUMERIC(10,2) NOT NULL DEFAULT 10,
            notes              TEXT,
            status             TEXT NOT NULL DEFAULT 'ACTIVE'
                               CHECK (status IN ('ACTIVE','PAUSED','ENDED')),
            created_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
            created_by         UUID
        )
    """))

    conn.execute(sa.text("""
        CREATE TABLE IF NOT EXISTS community.sponsored_seats (
            id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            sponsor_org_id        TEXT NOT NULL REFERENCES community.sponsor_orgs(id) ON DELETE CASCADE,
            code                  TEXT NOT NULL UNIQUE,
            status                TEXT NOT NULL DEFAULT 'AVAILABLE'
                                  CHECK (status IN ('AVAILABLE','REDEEMED','REVOKED')),
            redeemed_by_tenant_id UUID,
            redeemed_by_user_id   UUID,
            redeemed_farmer_name  TEXT,
            redeemed_farm_label   TEXT,
            redeemed_at           TIMESTAMPTZ,
            prev_tier             TEXT,
            prev_tis_daily_limit  INTEGER,
            created_at            TIMESTAMPTZ NOT NULL DEFAULT now(),
            created_by            UUID
        )
    """))
    conn.execute(sa.text(
        "CREATE INDEX IF NOT EXISTS ix_sponsored_seats_org ON community.sponsored_seats (sponsor_org_id)"))
    conn.execute(sa.text(
        "CREATE INDEX IF NOT EXISTS ix_sponsored_seats_status ON community.sponsored_seats (status)"))
    conn.execute(sa.text(
        "CREATE INDEX IF NOT EXISTS ix_sponsored_seats_redeemer ON community.sponsored_seats (redeemed_by_tenant_id)"))

    conn.execute(sa.text("""
        DO $$ BEGIN IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname='teivaka_app') THEN
            GRANT SELECT, INSERT, UPDATE, DELETE ON community.sponsor_orgs     TO teivaka_app;
            GRANT SELECT, INSERT, UPDATE, DELETE ON community.sponsored_seats  TO teivaka_app;
        END IF; END $$
    """))


def downgrade():
    conn = op.get_bind()
    conn.execute(sa.text("DROP TABLE IF EXISTS community.sponsored_seats"))
    conn.execute(sa.text("DROP TABLE IF EXISTS community.sponsor_orgs"))
