"""177 — marketplace transaction-fee capture (Product 4 / largest channel)

The platform never holds the money (no in-platform settlement), so fees are
ACCRUED as a platform receivable on genuine marketplace sales — mirroring the
affiliate-commission accrual pattern. The farmer's cash_ledger is untouched; the
fee ledger is Teivaka's revenue record (later invoiced/collected out-of-band).

Two global config/ledger tables (community.* — no RLS, admin-writable):
  community.marketplace_fee_rates  — admin-editable % per category
  community.marketplace_fee_ledger — one accrued fee row per marketplace payment

Plus tenant.orders.is_marketplace_sale: fees accrue ONLY when an order is flagged
a marketplace sale — never on ordinary self-logged cash sales (no over-charging).

Seeds the ratified rates: Produce 2% · Inputs 3% · Services 5% · Labour 5%.
Additive/idempotent; reversible. Apply as owner (Strike #123).

Revision ID: 177_marketplace_fees
Revises: 176_sponsored_plan_card
"""
from alembic import op
import sqlalchemy as sa

revision = "177_marketplace_fees"
down_revision = "176_sponsored_plan_card"
branch_labels = None
depends_on = None


def upgrade():
    conn = op.get_bind()

    conn.execute(sa.text("""
        CREATE TABLE IF NOT EXISTS community.marketplace_fee_rates (
            category    TEXT PRIMARY KEY,
            label       TEXT NOT NULL,
            fee_pct     NUMERIC(5,2) NOT NULL DEFAULT 0,
            is_active   BOOLEAN NOT NULL DEFAULT true,
            updated_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
            updated_by  UUID
        )
    """))
    conn.execute(sa.text("""
        INSERT INTO community.marketplace_fee_rates (category, label, fee_pct, is_active)
        VALUES
            ('PRODUCE','Produce Marketplace', 2, true),
            ('INPUTS','Input Marketplace',   3, true),
            ('SERVICES','Service Marketplace',5, true),
            ('LABOUR','Labour Marketplace',  5, true)
        ON CONFLICT (category) DO NOTHING
    """))

    conn.execute(sa.text("""
        CREATE TABLE IF NOT EXISTS community.marketplace_fee_ledger (
            id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            tenant_id        UUID NOT NULL,
            order_id         TEXT,
            category         TEXT NOT NULL,
            gross_amount_fjd NUMERIC(12,2) NOT NULL,
            fee_pct          NUMERIC(5,2)  NOT NULL,
            fee_amount_fjd   NUMERIC(12,2) NOT NULL,
            status           TEXT NOT NULL DEFAULT 'ACCRUED'
                             CHECK (status IN ('ACCRUED','INVOICED','PAID','WAIVED')),
            source_ledger_id TEXT,
            note             TEXT,
            created_at       TIMESTAMPTZ NOT NULL DEFAULT now()
        )
    """))
    conn.execute(sa.text(
        "CREATE INDEX IF NOT EXISTS ix_mkt_fee_ledger_tenant ON community.marketplace_fee_ledger (tenant_id)"))
    conn.execute(sa.text(
        "CREATE INDEX IF NOT EXISTS ix_mkt_fee_ledger_status ON community.marketplace_fee_ledger (status)"))
    conn.execute(sa.text(
        "CREATE INDEX IF NOT EXISTS ix_mkt_fee_ledger_created ON community.marketplace_fee_ledger (created_at)"))

    # Fees accrue only on flagged marketplace sales.
    conn.execute(sa.text(
        "ALTER TABLE tenant.orders ADD COLUMN IF NOT EXISTS is_marketplace_sale BOOLEAN NOT NULL DEFAULT false"))

    conn.execute(sa.text("""
        DO $$ BEGIN IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname='teivaka_app') THEN
            GRANT SELECT, INSERT, UPDATE, DELETE ON community.marketplace_fee_rates  TO teivaka_app;
            GRANT SELECT, INSERT, UPDATE, DELETE ON community.marketplace_fee_ledger TO teivaka_app;
        END IF; END $$
    """))


def downgrade():
    conn = op.get_bind()
    conn.execute(sa.text("ALTER TABLE tenant.orders DROP COLUMN IF EXISTS is_marketplace_sale"))
    conn.execute(sa.text("DROP TABLE IF EXISTS community.marketplace_fee_ledger"))
    conn.execute(sa.text("DROP TABLE IF EXISTS community.marketplace_fee_rates"))
