"""181 — platform billing: turn accrued fees into collectible invoices

Aggregates the two platform receivables — marketplace fees
(community.marketplace_fee_ledger, status ACCRUED) and self-serve sponsor
placements (community.sponsor_placements, payment_status UNPAID) — into invoice
documents with a DRAFT→SENT→PAID lifecycle. Back-links (invoice_id on each
source row) make paying an invoice flip its source rows, and voiding release them.

Additive/idempotent; reversible. Apply as owner (Strike #123).

Revision ID: 181_platform_invoices
Revises: 180_order_marketplace_category
"""
from alembic import op
import sqlalchemy as sa

revision = "181_platform_invoices"
down_revision = "180_order_marketplace_category"
branch_labels = None
depends_on = None


def _exec_each(statements):
    conn = op.get_bind()
    for s in statements:
        conn.execute(sa.text(s))


def upgrade():
    _exec_each([
        """
        CREATE TABLE IF NOT EXISTS community.platform_invoices (
            invoice_id     TEXT PRIMARY KEY,
            tenant_id      UUID NOT NULL,
            account_label  TEXT,
            period_start   DATE,
            period_end     DATE,
            status         TEXT NOT NULL DEFAULT 'DRAFT'
                           CHECK (status IN ('DRAFT','SENT','PAID','VOID')),
            subtotal_fjd   NUMERIC(12,2) NOT NULL DEFAULT 0,
            total_fjd      NUMERIC(12,2) NOT NULL DEFAULT 0,
            currency       TEXT NOT NULL DEFAULT 'FJD',
            due_date       DATE,
            issued_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
            sent_at        TIMESTAMPTZ,
            paid_at        TIMESTAMPTZ,
            payment_ref    TEXT,
            note           TEXT,
            created_by     UUID,
            created_at     TIMESTAMPTZ NOT NULL DEFAULT now()
        )
        """,
        """
        CREATE TABLE IF NOT EXISTS community.platform_invoice_lines (
            id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            invoice_id   TEXT NOT NULL REFERENCES community.platform_invoices(invoice_id) ON DELETE CASCADE,
            source_type  TEXT NOT NULL,   -- MARKETPLACE_FEE | SPONSOR_PLACEMENT
            source_id    TEXT NOT NULL,
            description  TEXT NOT NULL,
            amount_fjd   NUMERIC(12,2) NOT NULL,
            created_at   TIMESTAMPTZ NOT NULL DEFAULT now()
        )
        """,
        "CREATE INDEX IF NOT EXISTS ix_platform_invoices_tenant ON community.platform_invoices (tenant_id)",
        "CREATE INDEX IF NOT EXISTS ix_platform_invoices_status ON community.platform_invoices (status)",
        "CREATE INDEX IF NOT EXISTS ix_platform_invoice_lines_inv ON community.platform_invoice_lines (invoice_id)",
        "ALTER TABLE community.marketplace_fee_ledger ADD COLUMN IF NOT EXISTS invoice_id TEXT",
        "ALTER TABLE community.sponsor_placements ADD COLUMN IF NOT EXISTS invoice_id TEXT",
        """
        DO $$ BEGIN IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname='teivaka_app') THEN
            GRANT SELECT, INSERT, UPDATE, DELETE ON community.platform_invoices      TO teivaka_app;
            GRANT SELECT, INSERT, UPDATE, DELETE ON community.platform_invoice_lines TO teivaka_app;
        END IF; END $$
        """,
    ])


def downgrade():
    _exec_each([
        "ALTER TABLE community.sponsor_placements DROP COLUMN IF EXISTS invoice_id",
        "ALTER TABLE community.marketplace_fee_ledger DROP COLUMN IF EXISTS invoice_id",
        "DROP TABLE IF EXISTS community.platform_invoice_lines",
        "DROP TABLE IF EXISTS community.platform_invoices",
    ])
