-- Run after 01_shared_schema.sql to populate initial Knowledge Base
-- Embeddings are NULL here — generated by ai_worker.embed_kb_article task
-- 25 articles covering core agronomic topics for Fiji smallholder operations

INSERT INTO shared.kb_articles (kb_entry_id, title, content, category, production_id, rag_status, tags, language, source, version)
VALUES (
    'KB-001',
    'Tomato Production in Fiji — Complete Guide',
    'Tomatoes (Lycopersicon esculentum) are one of the highest-value vegetable crops in Fiji, commanding FJD 2.50–4.00/kg at Suva Municipal Market. In the Teivaka system, tomatoes are classified as CRP-TOM under the Solanaceae family.

PLANTING: Raise seedlings in nursery trays for 4–6 weeks before transplanting. Ideal transplant spacing is 50cm between plants, 75cm between rows, giving approximately 26,000 plants per hectare. In Fiji''s humid conditions, maintain adequate spacing for air circulation to prevent fungal disease. Plant into raised beds (30cm height) for drainage in heavy Serua clay soils.

CLIMATE: Tomatoes perform best at 20–28°C. Fiji''s wet season (November–April) brings high humidity and disease pressure — Fusarium wilt and early blight are primary threats. Dry season planting (May–October) gives the best results in Serua. In Kadavu, the microclimate is more consistently humid — use disease-resistant varieties like Tengeru 97 or AVRDC hybrids.

FERTILIZATION: Apply base dressing of 10:20:20 NPK at 200kg/ha before transplanting. Side-dress with urea (46-0-0) at 50kg/ha at first flower. Calcium nitrate spray (2g/L) prevents blossom end rot, which is common in Fiji during dry spells.

ROTATION RULES: Tomatoes are Solanaceae family. Under Teivaka rotation rules, a minimum 60-day rest period is REQUIRED before replanting any Solanaceae crop. This prevents Fusarium oxysporum f.sp. lycopersici buildup, which persists in soil for 5–10 years. Best rotation sequences: tomato → cassava → sweet potato → tomato (30-month cycle).

HARVEST: First harvest at 70–85 days from transplant. Harvest 2–3 times per week at mature green stage for market delivery. Expected yield: 20,000–35,000 kg/ha under good management. Teivaka target CoKG for tomato: under FJD 2.00/kg.',
    'CROP_MANAGEMENT',
    'CRP-TOM',
    'VALIDATED',
    ARRAY['tomato', 'Solanaceae', 'Fusarium', 'planting', 'Fiji', 'rotation'],
    'en',
    'Teivaka Agronomy Team v1.0',
    1
) ON CONFLICT (kb_entry_id) DO NOTHING;

INSERT INTO shared.kb_articles (kb_entry_id, title, content, category, production_id, rag_status, tags, language, source, version)
VALUES (
    'KB-002',
    'Eggplant (Baingan) Production in Fiji',
    'Eggplant (Solanum melongena), known locally as baingan or baigani, is a major crop for Indo-Fijian farming communities. It is classified under Solanaceae and shares rotation restrictions with tomato, capsicum, and chilli. Market prices range from FJD 1.50–3.00/kg depending on variety, season, and market.

VARIETIES: For Fiji conditions, the best-performing varieties are Surya F1 (long purple), Black Beauty (round), and local landraces maintained by Fijian farmers for over 60 years. Surya F1 gives 30–40% higher yield than traditional varieties but requires purchased seed each season.

PLANTING: Transplant 35–40 day old seedlings at 60cm × 90cm spacing. Eggplant tolerates wetter conditions better than tomato but still requires well-drained beds. pH optimal range is 5.5–6.8. Mulching with dried cane trash or banana leaves reduces soil moisture loss and weed pressure.

PEST MANAGEMENT: The fruit and shoot borer (Leucinodes orbonalis) is the primary pest in Fiji — it tunnels into young shoots and developing fruit, causing up to 60% crop loss if unmanaged. Spray Dimethoate 40% EC at 2mL/L at 7-day intervals during fruiting. Always observe the 7-day PHI (Pre-Harvest Interval) for Dimethoate. Mancozeb (80% WP) at 2.5g/L controls fungal leaf spot.

FERTILIZATION: Apply FYM (farmyard manure) at 15 tonnes/ha before planting. Top-dress with CAN (calcium ammonium nitrate) at 100kg/ha at 30 and 60 days after transplant.

ROTATION: Minimum 60-day Solanaceae rest before replanting eggplant. Ideal successor crop is cassava or sweet potato (non-Solanaceae, soil-restorative).

HARVEST: Begin at 70–80 days after transplant. Harvest every 4–5 days at commercial size (18–22cm for long varieties). Avoid overripe fruit — it becomes bitter and unsaleable. Shelf life without refrigeration is 3–4 days in Fiji''s heat. Total season yield: 25,000–40,000 kg/ha with good management.',
    'CROP_MANAGEMENT',
    'CRP-EGG',
    'VALIDATED',
    ARRAY['eggplant', 'baingan', 'Solanaceae', 'fruit-borer', 'Dimethoate', 'rotation'],
    'en',
    'Teivaka Agronomy Team v1.0',
    1
) ON CONFLICT (kb_entry_id) DO NOTHING;

INSERT INTO shared.kb_articles (kb_entry_id, title, content, category, production_id, rag_status, tags, language, source, version)
VALUES (
    'KB-003',
    'Cassava (Tavioka) Production and Soil Health in Fiji',
    'Cassava (Manihot esculenta), called tavioka in Fijian, is the most important staple root crop in Fiji and is grown on virtually every farm. Beyond food security, cassava plays a critical agronomic role in crop rotation systems — it is a soil-improving break crop that suppresses soilborne pathogens affecting Solanaceae crops.

VARIETIES: The two dominant varieties in Fiji are Rewa cassava (high starch, 14–18 months maturity) and Aiwa cassava (faster at 10–12 months, suitable for coastal lowlands). For commercial starch production, Rayong 60 has been trialled successfully in Ba Province.

PLANTING: Plant stem cuttings (25–30cm, 4–6 nodes) at 1m × 1m spacing. Plant horizontally or at 45° angle in mounded ridges. Do not plant bare sticks in waterlogged ground — stem rot will occur. In Kadavu, plant at the start of the dry season (May–June) for October harvest.

SOIL PREPARATION: Cassava tolerates poor soils but responds dramatically to added potassium. Apply muriate of potash (MOP, 0-0-60) at 100kg/ha or wood ash at 2 tonnes/ha. Cassava acidifies soil over time — measure pH after harvest and lime to maintain 5.5–6.5.

ROTATION ROLE: Cassava''s deep root system breaks hardpan layers (important in Serua compacted soils). It does not harbor Fusarium oxysporum or Phytophthora species that damage tomatoes. A 6–12 month cassava phase between Solanaceae crops reduces soilborne disease pressure by an estimated 40–60% based on SPC regional trials.

HARVEST: Rewa variety: 14–18 months. Fresh weight yield: 25–45 tonnes/ha. Post-harvest, roots must be processed or sold within 48 hours or they deteriorate. For market, aim for 10–20cm diameter uniform tubers.

COST: At Teivaka benchmark rates, cassava CoKG is approximately FJD 0.35–0.55/kg — the lowest of any crop in the system. Useful as a cash flow crop during Solanaceae rest periods.',
    'CROP_MANAGEMENT',
    'CRP-CAS',
    'VALIDATED',
    ARRAY['cassava', 'tavioka', 'rotation', 'root-crop', 'soil-health', 'Fiji'],
    'en',
    'Teivaka Agronomy Team v1.0',
    1
) ON CONFLICT (kb_entry_id) DO NOTHING;

INSERT INTO shared.kb_articles (kb_entry_id, title, content, category, production_id, rag_status, tags, language, source, version)
VALUES (
    'KB-004',
    'Kava (Yaqona) Production Guide for Fiji Farmers',
    'Kava (Piper methysticum) is Fiji''s most culturally and economically significant crop. Dried kava (waka — lateral roots) fetches FJD 35–60/kg at Suva markets and up to USD 150/kg for export-grade product. It is a 3–5 year investment that requires patience and correct establishment.

ECOLOGY: Kava grows best at 400–800m elevation in Fiji (Nadroga highlands, Namosi, interior Viti Levu). At sea level, it is susceptible to Phytophthora root rot in wet conditions. Ideal rainfall is 2,000–3,000mm/year, well-distributed. Direct sun scorches leaves — plant under partial shade (50% shade cloth or secondary forest canopy).

PLANTING: Propagate from lateral stem cuttings (2–3 nodes, 15–20cm length). Plant in pits 50cm × 50cm × 30cm, enriched with compost at 5kg/pit. Spacing: 1.5m × 2m = 3,333 plants/ha. Keep weeded for the first 18 months — weed competition is the primary yield reducer in kava.

NUTRITION: Kava responds strongly to phosphorus. Apply rock phosphate at 200kg/ha at planting. Top-dress with NPK 12:12:17 at 100kg/ha at 12 months. Organic mulching (banana pseudostem, leaf litter) conserves moisture and adds nutrition over time.

DISEASE: Phytophthora kava root rot is the most serious threat. Symptoms: yellowing, wilting, black roots. No chemical cure once established — prevention is critical. Ensure site drainage is excellent. Avoid planting where kava has previously rotted.

HARVEST: Waka (lateral roots) provide the highest-value product. Harvest at 3–5 years for waka. Wash and sun-dry to 12–14% moisture. Grade into: lawena (very fine), waka (standard), lewena (leaf mix). Waka commands the highest price.

MARKET NOTE: Teivaka farms exporting kava must comply with Fiji Kava Act 2020 and Kava Decree. All exports require SPC-certified phytosanitary certificate. Document all harvest batches.',
    'CROP_MANAGEMENT',
    'CRP-KAV',
    'VALIDATED',
    ARRAY['kava', 'yaqona', 'export', 'Phytophthora', 'shade', 'Fiji-Kava-Act'],
    'en',
    'Teivaka Agronomy Team v1.0',
    1
) ON CONFLICT (kb_entry_id) DO NOTHING;

INSERT INTO shared.kb_articles (kb_entry_id, title, content, category, production_id, rag_status, tags, language, source, version)
VALUES (
    'KB-005',
    'Dalo (Taro) Production — Wetland and Dryland Methods',
    'Dalo (Colocasia esculenta) is Fiji''s premier cultural food crop and a major export commodity. Fiji exports both fresh dalo and taro chips to New Zealand, Australia, and Pacific Island communities. Two main types are grown: dalo ni tana (lowland/wetland) and dalo ni Haka (highland, smaller corm, more flavourful).

WETLAND DALO: Grown in flooded paddies (lovu), particularly in the Rewa Delta, Ba, and Sigatoka Valley. Plant suckers or huli (top cuttings) at 30cm × 45cm in flooded conditions. Maintain 5–10cm standing water throughout the growing period. Harvest at 8–12 months. Yield: 15,000–25,000 kg/ha.

DRYLAND DALO: Suitable for moist but not waterlogged conditions on hillsides. Requires 1,500mm+ annual rainfall or supplemental irrigation. Spacing 60cm × 60cm on mounded ridges. Mulch heavily with grass cuttings. Harvest at 9–14 months. Yield: 10,000–18,000 kg/ha.

SOIL REQUIREMENTS: pH 5.5–7.0. Dalo is a heavy potassium feeder — apply MOP at 150kg/ha or copious organic matter (coconut husk, banana leaves). Iron and zinc deficiencies are common on Serua acid soils — apply zinc sulfate foliar spray (0.5g/L) at 60 days.

PESTS AND DISEASES: Taro leaf blight (Phytophthora colocasiae) is the most destructive disease in Fiji, capable of destroying 95% of a crop in 2 weeks during wet season. Symptoms: dark water-soaked lesions on leaves spreading rapidly. Control: Ridomil (Metalaxyl + Mancozeb) at 2.5g/L, spray at first sign. Resistant varieties from SPC Regional Germplasm Centre (Taisi, Niue, Samoa collections) are strongly recommended.

EXPORT COMPLIANCE: Export-grade dalo must be free of soil, meet minimum corm size (250g), and have phytosanitary clearance from Biosecurity Authority of Fiji (BAF).',
    'CROP_MANAGEMENT',
    'CRP-DAL',
    'VALIDATED',
    ARRAY['dalo', 'taro', 'wetland', 'dryland', 'Phytophthora', 'export', 'BAF'],
    'en',
    'Teivaka Agronomy Team v1.0',
    1
) ON CONFLICT (kb_entry_id) DO NOTHING;

INSERT INTO shared.kb_articles (kb_entry_id, title, content, category, production_id, rag_status, tags, language, source, version)
VALUES (
    'KB-006',
    'Pineapple Production in Fiji — Nadroga to Ba',
    'Pineapple (Ananas comosus) is grown commercially in Fiji primarily in Nadroga-Navosa, Ba, and Tailevu provinces. The main variety is Smooth Cayenne, used for both fresh market and juice processing. Farm-gate price for fresh pineapple ranges from FJD 0.80–1.50/kg depending on size and season.

ESTABLISHMENT: Propagate from crowns, slips, or ratoon suckers. Crown planting takes longer (18–24 months to first fruit) but produces larger fruit. Slip planting matures in 15–18 months. Plant on ridges or raised beds at 30cm × 60cm (double row system), giving 55,000 plants/ha.

SOIL: Pineapple thrives in sandy loam, pH 4.5–5.5 — one of the most acid-tolerant crops. Do not lime pineapple paddocks. Tolerates low-fertility soils but responds to applications of potassium and sulphur.

NUTRITION: Nitrogen is critical for canopy development. Apply urea via liquid injection or foliar spray at 100kg N/ha/year split into 4 applications. Foliar iron spray (ferrous sulfate 0.5g/L) corrects yellow-orange leaf tip chlorosis (iron deficiency), common on Fiji volcanic soils.

WATER: Pineapple is drought-tolerant but requires 1,000–1,500mm/year rainfall. In dry Nadroga (800mm/year), supplemental drip irrigation at key growth stages (flower induction, fruit development) significantly increases yield.

FLOWERING CONTROL: Ethylene gas or acetylene water (calcium carbide solution: 4g CaC₂ per 10L water, applied at night into the heart) induces uniform flowering and synchronizes harvest timing. This is standard practice on commercial Fiji farms.

HARVEST: Harvest at 120–140 days after flower induction. Fruit should be 1/4 to 1/2 yellow on shell. Fresh fruit shelf life in Fiji heat: 5–7 days. For export to Nadi resorts, harvest more mature at 3/4 yellow.

ECONOMICS: Pineapple has a low CoKG (FJD 0.40–0.65/kg) and is a good revenue stabilizer between higher-value vegetable cycles.',
    'CROP_MANAGEMENT',
    'CRP-PIN',
    'VALIDATED',
    ARRAY['pineapple', 'Smooth-Cayenne', 'Nadroga', 'flower-induction', 'ethylene', 'Fiji'],
    'en',
    'Teivaka Agronomy Team v1.0',
    1
) ON CONFLICT (kb_entry_id) DO NOTHING;

INSERT INTO shared.kb_articles (kb_entry_id, title, content, category, production_id, rag_status, tags, language, source, version)
VALUES (
    'KB-007',
    'Banana Production in Fiji — Varieties, Spacing, Disease Management',
    'Banana (Musa spp.) is the most widely grown fruit crop in Fiji, present on virtually every smallholder farm. Commercial production for Suva Market centers on Cavendish (Williams) and local varieties (Senikau, Popolu). Export-grade Cavendish goes to Nadi resort hotels at FJD 1.80–2.50/kg.

VARIETIES FOR FIJI:
- Williams Cavendish: Export-quality, preferred by resorts. Requires wind protection. Plant at 3m × 3m.
- Senikau: Traditional Fijian variety, hardy, low input, suited for remote islands. Good for local market.
- Popolu: Large plantain-type, eaten cooked. High demand in iTaukei communities.
- Dwarf Cavendish: Wind-resistant, 1.5m height, better for exposed coastal areas of Kadavu.

PLANTING: Use disease-free suckers or tissue culture plantlets. Sword suckers (narrow leaves, solid base) are preferred over water suckers. Remove all suckers except the designated follower (next generation plant). A well-managed stool can produce for 5+ years.

SOIL AND NUTRITION: Bananas are potassium-demanding. Apply MOP at 300kg/ha/year. Nitrogen at 200kg N/ha/year in 6 split doses. Deficiency symptoms: purple leaf margins (Mg), yellowing (N or Mg), stunting (K or Fe).

DISEASE — SIGATOKA LEAF SPOT: Black Sigatoka (Mycosphaerella fijiensis) is endemic in Fiji and causes significant yield loss. Weekly oil-based fungicide sprays (summer) or fortnightly (dry season) are standard on commercial farms. Organic option: Bordeaux mixture (1:1:100 copper sulfate:lime:water) every 10 days.

DISEASE — FUSARIUM WILT (PANAMA DISEASE TR4): Tropical Race 4 has not been confirmed in Fiji as of 2024 but remains a biosecurity threat. Report any sudden wilt of Cavendish to BAF immediately. Do NOT move planting material between farms without inspection.

HARVEST: Harvest 10–14 weeks after bunch emergence. Ideal for market: full-finger plumpness, green peel, no splitting. Transport in padded field boxes to prevent bruising.',
    'CROP_MANAGEMENT',
    'CRP-BAN',
    'VALIDATED',
    ARRAY['banana', 'Cavendish', 'Sigatoka', 'Fusarium', 'TR4', 'BAF', 'Fiji'],
    'en',
    'Teivaka Agronomy Team v1.0',
    1
) ON CONFLICT (kb_entry_id) DO NOTHING;

INSERT INTO shared.kb_articles (kb_entry_id, title, content, category, production_id, rag_status, tags, language, source, version)
VALUES (
    'KB-008',
    'Watermelon Production in Fiji — High-Value Summer Crop',
    'Watermelon (Citrullus lanatus) is a high-value cash crop in Fiji, commanding FJD 2.50–5.00/kg at peak season (September–December). It is best grown in the drier western division (Nadroga, Ba, Nadi areas) during the dry season. Humidity and prolonged rain during fruit set causes fruit cracking and fungal rots.

VARIETIES: Sugar Baby (small 3–5kg, high Brix, preferred for local markets), Crimson Sweet (8–12kg, popular at resorts), and Jubilee (striped, 10–15kg, good for bulk market). Choose based on market destination and available storage.

SOIL: Deep sandy loam, pH 6.0–7.0. Watermelon will not tolerate waterlogging — ridged beds essential. Avoid fields with a previous cucurbit crop within 2 years (Phytophthora and Fusarium risk).

PLANTING: Direct seed at 2–3 seeds per hill, 2m × 3m spacing (1,666 hills/ha). Thin to 1 plant per hill at 2-leaf stage. Sow seeds 2–3cm deep. Pre-soak in water for 4 hours before planting to improve germination.

POLLINATION: Watermelon requires insect pollination (honeybee). If you see poor fruit set, poor berry shape, or hollow centers, introduce hive boxes at 2 hives/ha at first flower. Do not spray insecticide during open flower hours (6am–12pm).

IRRIGATION: Furrow irrigate weekly during vine growth, reduce to every 10 days during fruit development. Stop irrigation 7–10 days before harvest to concentrate sugar (Brix) and prevent splitting.

PESTS: Aphids transmit Watermelon Mosaic Virus — control with Imidacloprid (Confidor) 0.5mL/L. Powdery mildew in dry season — spray sulfur-based fungicide (Thiovit 80% WP at 2g/L).

HARVEST: Tap the fruit — hollow sound indicates ripeness. Check the tendril near fruit — when dry and brown, fruit is ready. Shelf life: 2–3 weeks at ambient Fiji temperatures.',
    'CROP_MANAGEMENT',
    'CRP-WAT',
    'VALIDATED',
    ARRAY['watermelon', 'Citrullus', 'dry-season', 'pollination', 'Brix', 'Fiji'],
    'en',
    'Teivaka Agronomy Team v1.0',
    1
) ON CONFLICT (kb_entry_id) DO NOTHING;

INSERT INTO shared.kb_articles (kb_entry_id, title, content, category, production_id, rag_status, tags, language, source, version)
VALUES (
    'KB-009',
    'Sweet Potato (Kumala) — Fiji''s Versatile Root Crop',
    'Sweet potato (Ipomoea batatas), called kumala in Fijian, is widely grown across all Fiji islands as a fast-maturing, drought-tolerant food and cash crop. It matures in 3–5 months, making it ideal as a bridge crop between longer-duration crops. Market price: FJD 0.80–1.50/kg at Suva Municipal.

VARIETIES IN FIJI:
- SPFM 1 (Fiji Orange): High beta-carotene, moist flesh. Popular with NCD-awareness programs and schools.
- Wainimakutu White: Traditional Fijian variety, dry starch flesh, preferred for baking.
- Wagilevu Purple: Anthocyanin-rich, premium market niche product.
- SPC CIP varieties: Tested by SPC for yield and virus resistance — ask your local Ministry of Agriculture extension office for certified planting material.

PLANTING: Use healthy vine cuttings (20–30cm, 4–6 nodes). Plant at 30cm × 60cm spacing on mounded ridges (30cm height). Bury 2–3 nodes underground — these form the storage roots.

SOIL: Tolerates poor soils but yields best in sandy loam, pH 5.5–6.5. Excess nitrogen causes excessive vine growth at the expense of root development — limit N application to 30–40kg N/ha total.

WEED CONTROL: Critical in first 4–6 weeks before vine closure. Once vines close, they suppress weeds naturally.

PESTS: Weevils (Cylas formicarius) are the primary storage pest — tunnel into roots. Use pheromone traps at harvest time. Store harvested kumala in cool, dry, dark conditions. Do not store damaged roots.

ROTATION: Sweet potato is an excellent rotation crop after Solanaceae crops. Its different soil microbial stimulation and rapid vine coverage suppress weeds and reduce pest pressure. A sweet potato cycle in between tomato seasons reduces Fusarium spore load by an estimated 25%.

HARVEST: Harvest at 90–150 days depending on variety. Cure roots at 30°C for 4 days before storage to harden skin.',
    'CROP_MANAGEMENT',
    'CRP-SWP',
    'VALIDATED',
    ARRAY['sweet-potato', 'kumala', 'Ipomoea', 'rotation', 'weevil', 'Fiji'],
    'en',
    'Teivaka Agronomy Team v1.0',
    1
) ON CONFLICT (kb_entry_id) DO NOTHING;

INSERT INTO shared.kb_articles (kb_entry_id, title, content, category, production_id, rag_status, tags, language, source, version)
VALUES (
    'KB-010',
    'Green Beans Production for Fiji Hotels and Export',
    'Green beans (Phaseolus vulgaris) are a high-value vegetable crop in Fiji primarily targeting resort hotels, supermarkets, and export to New Zealand. Nadi hotel buyers pay FJD 3.50–5.00/kg for premium Grade A beans (straight, uniform, no blemish). Production requires attention to timing, quality, and cold chain.

VARIETIES: Noval (stringless, bush type), Bronco (high yield, export-quality), Masterpiece (climbing, higher yield but needs trellising). Bush bean varieties are most practical for smallholder production in Fiji — no trellising cost.

SOIL AND PLANTING: Direct seed at 5cm depth, 5cm apart in rows 45cm apart. pH 6.0–7.0 optimal. Beans fix nitrogen (Rhizobium symbiosis) — inoculate seed with Rhizobium leguminosarum inoculant at planting if soil has not grown beans before. Do NOT over-apply nitrogen — this reduces pod set.

IRRIGATION: Beans are sensitive to both drought and waterlogging. Furrow irrigate at flower initiation (45 days) and pod fill (60 days). Overhead irrigation causes fungal disease — avoid if possible in Fiji''s humid climate.

DISEASE: Angular leaf spot (Phaeoisariopsis griseola) and bean rust (Uromyces phaseoli) are major threats in humid conditions. Spray Mancozeb 80% WP at 2.5g/L from first flower at 7-day intervals. PHI for Mancozeb is 5 days.

QUALITY STANDARDS FOR HOTEL MARKET: Beans must be straight (not curved), 8–12cm length, no rust spots, no mechanical damage. Harvest at pencil-width diameter. Hotels typically reject beans over 14cm (overmature, tougher). Deliver chilled in lidded bins within 12 hours of harvest.

HARVEST: First harvest at 55–65 days from planting. Harvest every 3 days to maintain quality and stimulate continued production. Total season: 6–8 weeks of harvest. Yield: 8,000–12,000 kg/ha.

COLD CHAIN NOTE: For export to New Zealand, green beans must be pre-cooled to 7°C within 4 hours of harvest and maintained at 5–8°C throughout transit. Biosecurity Authority of Fiji (BAF) inspection required.',
    'CROP_MANAGEMENT',
    'CRP-GRB',
    'VALIDATED',
    ARRAY['green-beans', 'Phaseolus', 'hotel-market', 'export', 'Mancozeb', 'cold-chain'],
    'en',
    'Teivaka Agronomy Team v1.0',
    1
) ON CONFLICT (kb_entry_id) DO NOTHING;

INSERT INTO shared.kb_articles (kb_entry_id, title, content, category, production_id, rag_status, tags, language, source, version)
VALUES (
    'KB-011',
    'Chinese Cabbage (Petsai) Production in Fiji',
    'Chinese cabbage (Brassica rapa subsp. pekinensis), known locally as petsai or chabai, is the fastest-growing leafy vegetable in the Teivaka crop portfolio, maturing in 45–65 days. It commands FJD 1.50–3.00/kg at Suva Municipal Market and is in consistent year-round demand. It is classified in Teivaka as CRP-CHC (Brassicaceae family).

VARIETIES: Tropical Pride, Green Rocket, and local landrace selections adapted to Fiji. Tropical Pride is most heat-tolerant and least susceptible to bolting.

PLANTING: Transplant 15–18 day seedlings at 30cm × 40cm spacing. Plant in well-prepared beds with good drainage. Direct seeding at 1cm depth, 15cm apart in rows, thinning to 30cm final spacing.

SOIL: pH 6.0–7.0. Brassicas respond strongly to calcium — apply dolomite lime before planting if pH is below 6.0. Boron deficiency causes hollow stem and brown heart — apply borax (sodium tetraborate) at 2kg/ha as soil application.

PESTS: Diamondback moth (Plutella xylostella) is the most destructive pest of Chinese cabbage in Fiji. Larvae skeletonize leaves. Resistance to synthetic pyrethroids is widespread — use Spinosad (Success) at 0.5mL/L or Bacillus thuringiensis (Bt) as biological control. Rotate chemical groups to prevent resistance buildup.

DISEASE: Clubroot (Plasmodiophora brassicae) is a soil pathogen causing severe root galling. There is NO chemical treatment after infection. Prevention: maintain soil pH above 6.5 (lime), practice minimum 2-year Brassicaceae rotation break, and never move soil from infected areas.

ROTATION: Minimum 60-day rest from any Brassicaceae crop (cabbage, cauliflower, mustard, radish). Best rotation sequence: petsai → tomato → cassava → petsai.

HARVEST: Harvest when head is firm, compact, and 1.5–2.5kg. Cut at soil level with clean knife. Pack unwashed into bags for market — moisture accelerates rot.',
    'CROP_MANAGEMENT',
    'CRP-CHC',
    'VALIDATED',
    ARRAY['chinese-cabbage', 'petsai', 'Brassicaceae', 'diamondback-moth', 'clubroot', 'Spinosad'],
    'en',
    'Teivaka Agronomy Team v1.0',
    1
) ON CONFLICT (kb_entry_id) DO NOTHING;

INSERT INTO shared.kb_articles (kb_entry_id, title, content, category, production_id, rag_status, tags, language, source, version)
VALUES (
    'KB-012',
    'Mancozeb Application — Safe Use, PHI, and Compliance in Fiji',
    'Mancozeb (EBDC — Ethylene-bis-dithiocarbamate, 80% WP) is the most widely used broad-spectrum protectant fungicide in Fiji. It is registered under the Fiji Pesticides Act (Cap 114) for use on vegetables, banana, and root crops. Understanding correct use is critical for food safety and legal compliance.

WHAT MANCOZEB CONTROLS: Dalo leaf blight (Phytophthora colocasiae), banana Black Sigatoka (Mycosphaerella fijiensis), tomato early blight (Alternaria solani), tomato late blight (Phytophthora infestans), bean rust, downy mildew on cucumbers and watermelon.

APPLICATION RATE: Standard rate is 2.0–2.5g per litre of water. This gives 1.6–2.0g active ingredient per litre. Do not exceed maximum application rate — residue above the MRL (Maximum Residue Limit) of 5mg/kg creates export rejection risk.

PRE-HARVEST INTERVAL (PHI): Mancozeb has a 5-day PHI on most vegetables and a 7-day PHI on banana. This means the last spray must be at least 5 days before harvest. Record all spray dates in Teivaka input_transactions — the system can calculate PHI compliance automatically.

PROTECTIVE EQUIPMENT: Always wear rubber gloves, a face mask, and protective clothing when mixing and applying. Do not spray in wind above 15 km/h. Avoid spraying when bees are active (dawn to noon). Mancozeb has low mammalian toxicity (WHO Class U) but chronic exposure causes thyroid disruption.

MIXING INSTRUCTIONS: Fill spray tank 2/3 full with water. Add Mancozeb powder slowly while agitating. Fill to full volume. Spray within 4 hours of mixing. Never mix with alkaline products (lime, Bordeaux mixture) — inactivates the fungicide.

STORAGE AND DISPOSAL: Store in original container, sealed, dry place out of reach of children. Empty containers must be triple-rinsed and disposed at the Fiji Solid Waste Authority facility or punctured to prevent reuse. Never burn pesticide containers.

RESISTANCE MANAGEMENT: Mancozeb is a multi-site inhibitor — resistance development is extremely slow. It can be used as an anchor product in rotation programs with more specific fungicides.',
    'COMPLIANCE',
    NULL,
    'VALIDATED',
    ARRAY['Mancozeb', 'fungicide', 'PHI', 'pesticide-compliance', 'Fiji-Pesticides-Act', 'MRL'],
    'en',
    'Teivaka Agronomy Team v1.0',
    1
) ON CONFLICT (kb_entry_id) DO NOTHING;

INSERT INTO shared.kb_articles (kb_entry_id, title, content, category, production_id, rag_status, tags, language, source, version)
VALUES (
    'KB-013',
    'Dimethoate Use, PHI Compliance, and Market Rejection Risk in Fiji',
    'Dimethoate (40% EC — organophosphate systemic insecticide) is widely used in Fiji for control of fruit and shoot borer on eggplant, aphids, mites, and scale insects. However, its systemic nature and relatively long PHI make it one of the highest-risk pesticides for causing market rejection at Suva Municipal, resort hotels, and especially for exports.

WHAT DIMETHOATE CONTROLS: Eggplant fruit and shoot borer (Leucinodes orbonalis), aphids on most vegetables, mites on crops, scale insects on citrus. It is a systemic chemical — absorbed into plant tissue, making it effective but dangerous for residues.

PHI (PRE-HARVEST INTERVAL): Dimethoate has a 7-day PHI on most vegetables in Fiji. This is NON-NEGOTIABLE. If you spray dimethoate today (Day 0), you CANNOT harvest until Day 7 (the day after the 7th full day, i.e. Day 8 in practical terms).

WHY THIS MATTERS: In October 2022, a Serua farmer had a consignment of eggplant rejected at Suva Municipal Market because Dimethoate residues exceeded the MRL of 0.02mg/kg. The entire 380kg consignment was condemned. Estimated loss: FJD 950. Teivaka''s input tracking system can prevent this by alerting when a spray is logged too close to a scheduled harvest.

CALCULATING COMPLIANCE: In Teivaka, log your Dimethoate spray as an input_transaction (transaction_type = APPLICATION). The system reads your cycle harvest target date and flags if application is within the 7-day PHI window. Always log spray dates in real time.

ALTERNATIVES TO REDUCE DIMETHOATE RELIANCE:
1. Spinosad (Success 120SC) — 1-day PHI, effective on shoot borer, WHO Class 5
2. Emamectin benzoate (Proclaim) — 3-day PHI on eggplant
3. Pheromone traps + kaolin clay for physical barrier
4. Bagging individual eggplants at commercial scale (labour-intensive but zero-chemical premium)

STORAGE: Dimethoate is moderately toxic (WHO Class II) — store locked, labeled, away from food. Do not apply within 50m of any water source or waterway.',
    'COMPLIANCE',
    'CRP-EGG',
    'VALIDATED',
    ARRAY['Dimethoate', 'PHI', 'organophosphate', 'market-rejection', 'MRL', 'eggplant', 'compliance'],
    'en',
    'Teivaka Agronomy Team v1.0',
    1
) ON CONFLICT (kb_entry_id) DO NOTHING;

INSERT INTO shared.kb_articles (kb_entry_id, title, content, category, production_id, rag_status, tags, language, source, version)
VALUES (
    'KB-014',
    'Crop Rotation Science — Why the Teivaka Rotation Rules Exist',
    'Crop rotation is the practice of growing different crop families in sequence on the same land, with deliberate rest periods between related crops. The Teivaka rotation engine enforces minimum rest periods between crop families — this article explains the science behind those rules.

THE PATHOGEN PROBLEM: Soilborne pathogens — fungi, bacteria, and nematodes — accumulate in soil when the same crop is grown repeatedly. They are host-specific: Fusarium oxysporum f.sp. lycopersici attacks tomatoes; Plasmodiophora brassicae attacks Brassicas. Without rotation, pathogen populations double or triple with each crop cycle, reducing yield by 30–70%.

KEY ROTATION FAMILIES IN TEIVAKA:
- Solanaceae (tomato, eggplant, capsicum, chilli): 60-day minimum rest between any two Solanaceae crops. Fusarium wilt, Verticillium wilt, and TSWV (Tomato Spotted Wilt Virus) all persist in plant debris.
- Brassicaceae (cabbage, cauliflower, Chinese cabbage, radish): 60-day rest minimum. Clubroot (Plasmodiophora) survives as resting spores for 10+ years in soil.
- Cucurbitaceae (watermelon, cucumber, pumpkin, bitter gourd): 45-day rest. Phytophthora and Fusarium crown rot.
- Leguminosae (beans, peas, peanuts): 30-day rest. Nitrogen-fixing — leaving roots in soil adds 40–80kg N/ha equivalent.
- Poaceae (corn, sugarcane): 30-day rest. Generally low disease carryover risk.
- Root crops (cassava, sweet potato, yam, taro — different families): 30–45 days based on species.

ALLEOPATHIC EFFECTS: Some crops suppress subsequent crops chemically. Sorghum releases dhurrin, which inhibits germination of following crops. Always check crop family compatibility before planting.

ROTATION AND SOIL HEALTH: Diverse rotations increase soil microbial diversity. Research from SPC Suva shows that 3-family rotation systems maintain 40% higher earthworm populations compared to monoculture plots — earthworms are a proxy indicator of healthy soil biology.

APPLYING TEIVAKA ROTATION: When you start a new cycle in Teivaka, the decision engine checks your field history and flags if the planned crop violates rotation rules. You will see a WARNING or BLOCKED alert. BLOCKED means the pathogen risk is too high to override without agronomist approval.',
    'CROP_MANAGEMENT',
    NULL,
    'VALIDATED',
    ARRAY['rotation', 'soil-health', 'Fusarium', 'Brassicaceae', 'Solanaceae', 'decision-engine'],
    'en',
    'Teivaka Agronomy Team v1.0',
    1
) ON CONFLICT (kb_entry_id) DO NOTHING;

INSERT INTO shared.kb_articles (kb_entry_id, title, content, category, production_id, rag_status, tags, language, source, version)
VALUES (
    'KB-015',
    'Fiji Pesticide Law — What Every Farmer Must Know',
    'All pesticide use in Fiji is regulated under the Pesticides Act (Cap 114) administered by the Biosecurity Authority of Fiji (BAF) and the Ministry of Agriculture. Using unregistered pesticides, exceeding MRLs, or failing to observe PHI can result in fines, criminal prosecution, and permanent market bans.

KEY LEGAL REQUIREMENTS:

1. ONLY USE REGISTERED PRODUCTS: Every pesticide used in Fiji must be registered with the BAF Pesticides Board. A full list is available at baf.com.fj. Importing unregistered pesticides (including products from Samoa, Vanuatu, or China) is a criminal offence under Cap 114.

2. LABEL COMPLIANCE: You must use pesticides in accordance with label directions. Applying at a higher rate than stated on the label is an offence. Using a product for a crop not listed on the label (off-label use) is illegal without BAF permit.

3. PRE-HARVEST INTERVALS (PHI): Harvesting produce before the PHI has elapsed is an offence that can result in condemned produce and prosecution. Key PHIs: Mancozeb 5–7 days, Dimethoate 7 days, Chlorpyrifos 7–14 days, Imidacloprid 7 days, Glyphosate 14 days before harvest.

4. MAXIMUM RESIDUE LIMITS (MRLs): Produce at market must meet Codex Alimentarius MRL standards, adopted by Fiji under the Food Safety Act 2003. Exceeding MRLs leads to produce seizure and possible prosecution of the farmer.

5. RECORD KEEPING: Under Section 18 of Cap 114, commercial growers must maintain spray records for 2 years. Teivaka automatically generates this record from input_transactions. Export a PDF from the Teivaka exports module for FRA/BAF audit.

6. STORAGE AND DISPOSAL: Pesticides must be stored in original labeled containers, in a locked facility. Disposal of expired chemicals must follow the National Hazardous Waste Management Authority guidelines. Triple-rinse empty containers before disposal.

PENALTIES: First offence for unregistered pesticide use: up to FJD 10,000 fine. Repeat offence or causing injury: up to FJD 50,000 and 2 years imprisonment (Cap 114, Section 27).',
    'COMPLIANCE',
    NULL,
    'VALIDATED',
    ARRAY['pesticide-law', 'BAF', 'Cap-114', 'MRL', 'PHI', 'compliance', 'Fiji-law'],
    'en',
    'Teivaka Agronomy Team v1.0',
    1
) ON CONFLICT (kb_entry_id) DO NOTHING;

INSERT INTO shared.kb_articles (kb_entry_id, title, content, category, production_id, rag_status, tags, language, source, version)
VALUES (
    'KB-016',
    'Labor Management in Fiji Farms — Legal Obligations and Best Practice',
    'Managing farm labor in Fiji requires compliance with the Employment Relations Act 2007 (ERA), the National Minimum Wage Order (current FJD 4.00/hour as of 2024), and workplace health and safety obligations under the Health and Safety at Work Act 1996. Non-compliance exposes farmers to fines, back-pay claims, and reputational damage.

MINIMUM WAGE: The National Minimum Wage in Fiji as of 2024 is FJD 4.00 per hour. For a standard 8-hour day, this is FJD 32.00 minimum. Teivaka''s default daily rate input enforces this floor — you will receive a warning if you enter a rate below FJD 32.00/day.

OVERTIME: Hours worked beyond 8 per day or 45 per week must be paid at 1.5x the ordinary rate under Section 61 of ERA. Log overtime hours separately in Teivaka labor_attendance — the system calculates overtime_pay_fjd automatically.

CASUAL vs PERMANENT EMPLOYMENT: Casual workers (less than 6 months continuous employment) have fewer protections but must still receive minimum wage and overtime. Workers employed for more than 6 continuous months are deemed permanent under ERA and are entitled to annual leave (2 weeks), sick leave (10 days), and termination notice (minimum 1 month).

FNPF (FIJI NATIONAL PROVIDENT FUND): All employers must contribute 10% of gross wages to FNPF on behalf of each employee. Employees contribute 8%. Deductions must be remitted monthly to FNPF. Failure to remit is a criminal offence. Register workers with FNPF using their FNPF ID. Casual and temporary workers are included if they work more than 4 days per month.

DOCUMENTATION: Keep attendance records, signed daily pay slips, and FNPF contribution records. Teivaka generates these records — export monthly labor reports in CSV for your accountant.

HEALTH AND SAFETY: Provide PPE (gloves, boots, hat) for pesticide handling at no cost to worker. Workers under 15 cannot be employed. Workers cannot operate machinery without training certification. Workers mixing or applying pesticides must receive a 30-minute chemical safety briefing annually.',
    'FINANCE',
    NULL,
    'VALIDATED',
    ARRAY['labor', 'ERA', 'minimum-wage', 'FNPF', 'overtime', 'compliance', 'Fiji-law'],
    'en',
    'Teivaka Agronomy Team v1.0',
    1
) ON CONFLICT (kb_entry_id) DO NOTHING;

INSERT INTO shared.kb_articles (kb_entry_id, title, content, category, production_id, rag_status, tags, language, source, version)
VALUES (
    'KB-017',
    'Irrigation Systems for Fiji Smallholder Farms',
    'Access to water is the primary productivity constraint on Fiji farms outside the wet season. This article covers irrigation system selection, setup, cost, and operational guidance for farms from 0.5ha to 10ha.

TYPES OF IRRIGATION SYSTEMS:

1. OVERHEAD SPRINKLER (IMPACT TYPE): Best for leafy vegetables, seedling nurseries, and open crops. Covers 12–16m diameter per head at 2–3 bar pressure. Cost: FJD 800–1,500 for a 0.5ha system. Risk: creates wet canopy conditions — increases fungal disease in humid Fiji conditions. Not recommended for tomato, eggplant, or potato.

2. DRIP IRRIGATION: Most water-efficient (85–90% efficiency vs 60% for furrow). Delivers water directly to root zone. Significantly reduces fungal disease compared to overhead. Cost: FJD 2,500–4,000 for 0.5ha system with timer, filter, and drip tape. Teivaka strongly recommends drip for Solanaceae crops. Suitable pressure: 0.5–1.5 bar.

3. FURROW/FLOOD IRRIGATION: Low cost, traditional method. Works for cassava, sweet potato, sugarcane, pineapple. Water runs between crop rows in shallow furrows. Requires flat land with slight slope (0.5–1%) for water movement. High water use — not suitable for water-scarce farms or island farms.

4. MICRO-SPRINKLER/FOGGER: Used in nurseries and kava production under shade cloth. Creates high humidity environment. Suitable for misting operations.

WATER SOURCE ASSESSMENT: Before investing in irrigation, assess: (a) groundwater depth (Fiji Agriculture Department water bore register), (b) seasonal stream flow — many streams dry up May–September in Nadroga and Ba, (c) rainfall — Eastern Fiji receives 3,000–5,000mm/year and may not need irrigation, Western Fiji receives 1,500–2,000mm and likely does.

WATER RIGHTS: Under the Water Resource Act 2019, abstracting more than 1,000 liters/day from any water body requires a Water Use Permit from the Water Authority of Fiji. For farm irrigation, this threshold is easily exceeded — obtain your permit before installation.

DRIP TAPE MAINTENANCE: Flush drip tape monthly. Clean the main filter (100 mesh screen) weekly during operation. Drip tape lifespan in Fiji UV conditions: 2–3 seasons. Replace when flow rate drops by 20%.',
    'CROP_MANAGEMENT',
    NULL,
    'VALIDATED',
    ARRAY['irrigation', 'drip', 'sprinkler', 'water', 'Fiji', 'Water-Resource-Act'],
    'en',
    'Teivaka Agronomy Team v1.0',
    1
) ON CONFLICT (kb_entry_id) DO NOTHING;

INSERT INTO shared.kb_articles (kb_entry_id, title, content, category, production_id, rag_status, tags, language, source, version)
VALUES (
    'KB-018',
    'Soil pH Management for Fiji Farms',
    'Soil pH is the single most important determinant of nutrient availability in Fiji soils. The optimal pH for most vegetables is 6.0–7.0. Most Fiji soils are naturally acid (pH 4.5–5.8) due to high rainfall leaching basic cations. Understanding and correcting soil pH is foundational to any fertilizer program.

WHY pH MATTERS:
- Below pH 5.5: Phosphorus becomes "locked up" in insoluble iron and aluminum phosphates — fertilizer is wasted. Manganese and aluminum become toxic.
- pH 5.5–6.5: Most nutrients are available. This is the sweet spot for Fiji vegetable production.
- Above pH 7.5: Iron, manganese, zinc, and boron become deficient — leaves yellow.

TESTING SOIL PH: Use a simple soil pH test kit (available from Morris Hedstrom Agricultural) or send samples to the Koronivia Research Station soil lab (FJD 15/sample). For Teivaka farms, test each production unit separately — pH can vary by 1.0 unit across a small farm.

LIMING TO RAISE PH:
- Agricultural lime (CaCO₃): Apply 1–4 tonnes/ha depending on soil buffer capacity and target pH. Takes 3–6 months for full effect.
- Dolomite lime (CaCO₃ + MgCO₃): Preferred if magnesium is also deficient (very common in Fiji volcanic soils). Apply at same rate.
- Hydrated lime (Ca(OH)₂): Faster acting but more expensive and burns plants if over-applied. Use for emergency pH correction only.

APPLICATION TIMING: Apply lime 4–6 weeks before planting to allow reaction time. Incorporate into the top 15cm with a cultivator or fork. Do not apply lime and fertilizer simultaneously — lime neutralizes nitrogen.

ACIDIFYING SOIL (WHEN NEEDED): For acid-loving crops (pineapple, blueberry) or if pH has gone too alkaline: apply elemental sulfur (S) at 200–500kg/ha. Takes 2–4 weeks for soil bacteria to convert to sulfuric acid. Sulfur of ammonia (ammonium sulfate) also acidifies slightly.

SERUA SOILS SPECIFICALLY: The dominant Serua soils are classified as Oxisols and Ultisols — highly weathered, naturally pH 4.5–5.5, with very high phosphorus fixation capacity. Annual lime applications of 1–2 tonnes/ha are typically needed on vegetable paddocks.',
    'CROP_MANAGEMENT',
    NULL,
    'VALIDATED',
    ARRAY['soil-pH', 'lime', 'dolomite', 'phosphorus', 'Fiji-soils', 'Serua'],
    'en',
    'Teivaka Agronomy Team v1.0',
    1
) ON CONFLICT (kb_entry_id) DO NOTHING;

INSERT INTO shared.kb_articles (kb_entry_id, title, content, category, production_id, rag_status, tags, language, source, version)
VALUES (
    'KB-019',
    'Composting and Organic Matter Management for Fiji Farms',
    'Organic matter is the foundation of soil health in Fiji''s tropical farming systems. High-quality compost built from farm waste can replace FJD 200–400/ha of synthetic fertilizer per year, while building soil structure that synthetic inputs cannot replicate.

WHAT TO COMPOST ON A FIJI FARM:
- Green materials (nitrogen-rich): Crop residues, weeds (seed-free), kitchen scraps, green grass clippings, fresh manure (chicken, pig, cattle)
- Brown materials (carbon-rich): Dry cane trash, coconut husks, dried banana leaves, rice/dalo straw, wood ash
- Avoid: Diseased plant material, toxic weeds like Siam weed (Chromolaena odorata) seeds, meat or fish scraps (attract pests)

HOT COMPOST METHOD (30-DAY CYCLE): Build pile at minimum 1.5m × 1.5m × 1m. Layer green and brown materials alternately at 1:3 ratio (1 part green to 3 parts brown by volume). Moisten each layer — compost should feel like a wrung-out sponge, not dripping. Turn pile every 5 days. Internal temperature should reach 55–65°C — this kills weed seeds and pathogens. Compost is ready when it smells earthy, is dark brown, and original materials are not recognizable.

WORM FARMING (VERMICOMPOST): Highly efficient method for farm kitchen waste and market waste. African night crawlers (Eudrilus eugeniae) are the best species for Fiji''s tropical conditions. Vermicompost has 5–10x the microbial activity of regular compost. Worm castings improve water retention in sandy soils dramatically. A 1m × 2m worm bed can process 2kg waste per day and produces 0.5kg high-value castings.

APPLICATION RATES: Apply finished compost at 5–10 tonnes/ha for vegetables, incorporated 2–3 weeks before planting. For perennials (kava, banana), apply as surface mulch at 4kg/plant/year. Compost applied at 10t/ha replaces approximately: 50kg N/ha, 25kg P₂O₅/ha, 80kg K₂O/ha (variable by compost quality).

BIOCHAR ADDITION: Adding biochar (coconut shell char, burned at low oxygen) at 2–3 tonnes/ha improves water retention and cation exchange capacity in Fiji''s leaching soils, particularly beneficial in sandy coastal areas. Biochar alone has low nutrient value — always combine with compost.',
    'CROP_MANAGEMENT',
    NULL,
    'VALIDATED',
    ARRAY['composting', 'organic-matter', 'vermicompost', 'biochar', 'soil-health', 'Fiji'],
    'en',
    'Teivaka Agronomy Team v1.0',
    1
) ON CONFLICT (kb_entry_id) DO NOTHING;

INSERT INTO shared.kb_articles (kb_entry_id, title, content, category, production_id, rag_status, tags, language, source, version)
VALUES (
    'KB-020',
    'Reading Your CoKG Report — How to Interpret and Improve Your Numbers',
    'The Cost of Goods per Kilogram (CoKG) is Teivaka''s primary farm performance metric. It answers the question: "How much did it cost you to produce each kilogram of crop?" Understanding CoKG is essential for pricing decisions, cost reduction, and comparing performance between cycles and seasons.

FORMULA: CoKG = (Total Labor Cost + Total Input Cost + Overhead Allocation) ÷ Total Harvest Kg

COMPONENTS:
1. Total Labor Cost: Sum of all daily_rate_fjd × days worked plus overtime for all workers during the cycle.
2. Total Input Cost: All APPLICATION-type input transactions during the cycle (seeds, fertilizer, pesticides, irrigation costs).
3. Overhead Allocation: A portion of farm fixed costs (equipment depreciation, land lease, water permit) allocated per cycle. Currently optional in Teivaka — set at farm level.
4. Total Harvest Kg: Total accepted (non-rejected) harvest weight for the cycle.

INTERPRETING YOUR CoKG:
- Tomato: Good < FJD 1.80/kg | Average FJD 1.80–2.50/kg | Poor > FJD 2.50/kg
- Eggplant: Good < FJD 1.20/kg | Average FJD 1.20–1.80/kg | Poor > FJD 1.80/kg
- Chinese cabbage: Good < FJD 0.80/kg | Average FJD 0.80–1.20/kg | Poor > FJD 1.20/kg
- Green beans: Good < FJD 1.50/kg | Average FJD 1.50–2.20/kg | Poor > FJD 2.20/kg
- Cassava: Good < FJD 0.50/kg | Average FJD 0.50–0.80/kg | Poor > FJD 0.80/kg

COMMON REASONS FOR HIGH CoKG:
1. Low yield (pest/disease damage, poor germination, drought) — same costs, less harvest
2. High labor cost relative to output — benchmark FJD 0.80–1.20/kg labor for vegetables
3. Excessive or poorly timed input applications — spray only when economic threshold is reached
4. High rejection rate at harvest — post-harvest CoKG rises if 20%+ is rejected

TREND ANALYSIS: The CoKG trend in Teivaka financials shows improvement over cycles. A downward trend confirms that management improvements are working. An upward trend is an early warning signal requiring investigation.',
    'FINANCE',
    NULL,
    'VALIDATED',
    ARRAY['CoKG', 'cost-of-goods', 'financials', 'performance', 'benchmarks', 'decision-engine'],
    'en',
    'Teivaka Agronomy Team v1.0',
    1
) ON CONFLICT (kb_entry_id) DO NOTHING;

INSERT INTO shared.kb_articles (kb_entry_id, title, content, category, production_id, rag_status, tags, language, source, version)
VALUES (
    'KB-021',
    'Nursery Management — Raising Healthy Seedlings in Fiji',
    'The nursery phase is the most critical investment in any cropping cycle. A poor start — weak, diseased, or stressed seedlings — cannot be corrected in the field. Strong seedlings transplanted at the right stage establish faster, close canopy earlier, and yield 15–25% more than stressed transplants.

NURSERY SETUP: Build a nursery house with 50% shade cloth roof and fine insect mesh sides (0.9mm mesh excludes aphids and thrips). Minimum size for a 1-hectare operation: 5m × 10m. Raise seedling trays on benches at 80cm height to prevent soil-borne inoculum splash.

GROWING MEDIA: Use a commercial seed-raising mix (coco-peat + perlite 3:1) or prepare your own: 2 parts sieved garden soil + 1 part well-composted cow manure + 1 part coarse river sand. Sterilize home-made mix by solarization (cover in clear plastic for 3 weeks in full sun) before use.

TRAY TYPES: 50-cell plastic trays for tomato, eggplant, capsicum (1 seed/cell). 128-cell for Chinese cabbage, broccoli, onion. 32-cell for watermelon and cucumber (larger root ball needed).

SEEDING: Plant seeds at the recommended depth (usually 1–2x the seed diameter). Cover with fine vermiculite or seed-raising mix. Water immediately with fine mist. Germination temperature for most Fiji crops: 22–30°C (ideal, no heating needed in Fiji lowlands).

WATERING: Water morning only — allow surface to partially dry by afternoon to reduce damping-off fungal risk. Use Mancozeb drench (1g/L) once at emergence if damping-off is a previous issue.

HARDENING OFF: 7–10 days before transplanting, reduce shade to 30%, reduce watering frequency, and expose to outdoor conditions. This reduces transplant shock and accelerates field establishment by 5–10 days.

TRANSPLANT TIMING:
- Tomato, eggplant, capsicum: 4–6 weeks, 4–6 true leaves
- Chinese cabbage: 2.5–3 weeks, 3 true leaves
- Watermelon: 2–2.5 weeks, 2 true leaves (minimum root disturbance)
- Beans, corn: Direct seed — do not transplant',
    'CROP_MANAGEMENT',
    NULL,
    'VALIDATED',
    ARRAY['nursery', 'seedlings', 'transplant', 'damping-off', 'shade-cloth', 'Fiji'],
    'en',
    'Teivaka Agronomy Team v1.0',
    1
) ON CONFLICT (kb_entry_id) DO NOTHING;

INSERT INTO shared.kb_articles (kb_entry_id, title, content, category, production_id, rag_status, tags, language, source, version)
VALUES (
    'KB-022',
    'Harvest Timing and Quality Standards for Fiji Markets',
    'Harvesting at the correct stage of maturity is as important as growing the crop correctly. Harvesting too early reduces weight and flavour; too late causes quality rejection at market, shorter shelf life, and waste. This guide covers harvest indicators and quality standards for major Fiji crops.

TOMATO: Harvest at the "mature green to breaker" stage for Suva Market delivery — fruit has reached full size, exterior shows slight colour change at blossom end. For hotel delivery (within 24 hours), harvest at "turning" (25–75% colour change). Never deliver fully red tomatoes to Suva — they are rejected as overripe. Expected shelf life at mature green: 7–10 days at ambient Fiji temperatures.

EGGPLANT: Harvest at 75–80% of maximum fruit size, skin is glossy and taut. Press with thumb — slight give, not hard or spongy. Overripe fruit (dull skin, large seed cavity, bitter) is unsaleable. Harvest every 4–5 days to prevent overmature fruit.

CHINESE CABBAGE: Head should feel firm and compact (no give when pressed). Weight 1.2–2.0kg for market-grade. Avoid harvesting after heavy rain — water-soaked outer leaves cause rapid rot in transit.

WATERMELON: Three indicators of ripeness — (1) tendril nearest fruit is dry and brown, (2) dull hollow sound when tapped, (3) pale yellow ground spot. Check all three before harvesting. Immature watermelon has white or pale ground spot, higher-pitched sound, and green tendril. Shelf life: 2–3 weeks.

GREEN BEANS: Harvest when pods are straight, firm, and seeds are barely visible through pod wall (pencil-width diameter). Hotels reject beans at "flat pod" stage. Harvest every 2–3 days once started.

CASSAVA: Lift test roots at 10–12 months (Aiwa variety) or 14–16 months (Rewa). Dig a test root — check for good starch content (white flesh, no blue/grey discolouration from HCN in bitter varieties). Cassava must be sold or processed within 48 hours of harvest.

TRANSPORT QUALITY: Padded crates, never burlap sacks, for tomato, eggplant, beans. Maximum fill height 30cm to prevent compression damage. Deliver early morning for Suva Market — arrive before 6am to secure best stall placement.',
    'CROP_MANAGEMENT',
    NULL,
    'VALIDATED',
    ARRAY['harvest', 'quality', 'market-standards', 'post-harvest', 'Suva-Market', 'Fiji'],
    'en',
    'Teivaka Agronomy Team v1.0',
    1
) ON CONFLICT (kb_entry_id) DO NOTHING;

INSERT INTO shared.kb_articles (kb_entry_id, title, content, category, production_id, rag_status, tags, language, source, version)
VALUES (
    'KB-023',
    'Pest Identification Field Guide — Key Fiji Farm Pests',
    'Early and accurate pest identification is the first step to effective, cost-efficient control. Misidentification leads to using the wrong pesticide — wasting money and potentially harming beneficial insects or creating resistance. This guide covers the 10 most damaging pests on Fiji farms.

1. FRUIT AND SHOOT BORER (Leucinodes orbonalis) — EGGPLANT: Tiny white moth, larvae are pink-white caterpillars. Infest shoots first (flagging/wilting shoots), then bore into fruit leaving small entry hole with frass. Control: Spinosad 0.5mL/L or Emamectin benzoate 0.4g/L. Remove and destroy infested shoots.

2. DIAMONDBACK MOTH (Plutella xylostella) — BRASSICAS: Small brown moth. Green caterpillars skeletonize leaf from underneath, leaving transparent windows. Often resistant to pyrethroids. Control: Bt (Bacillus thuringiensis) or Spinosad. Rotate chemical groups.

3. APHIDS (multiple species) — ALL CROPS: Soft-bodied, pear-shaped insects in clusters on undersides of young leaves. Cause curling and yellowing. Primary concern is virus transmission (TSWV, CMV, WMV). Control: Imidacloprid 0.5mL/L. Reflective mulch deters aphid landing. Natural enemies (ladybirds, parasitic wasps) suppress aphids — avoid broad-spectrum sprays.

4. WHITEFLY (Bemisia tabaci) — TOMATO, EGGPLANT, BEANS: Tiny white winged insects, fly up in clouds when plant is disturbed. Transmit Tomato Yellow Leaf Curl Virus (TYLCV). Control: Yellow sticky traps, Imidacloprid 0.5mL/L. Remove and burn severely infected plants.

5. RED SPIDER MITE (Tetranychus urticae) — CUCUMBER, WATERMELON, EGGPLANT: Microscopic, 0.5mm, red/orange. Cause stippled, bronzed leaf surface. Thrive in hot, dry conditions. Use a hand lens to confirm — two-spotted mites are visible as moving dots. Control: Wettable sulfur (Thiovit) 2g/L. Do not use when temperature above 32°C.

6. TARO LEAF BLIGHT (Phytophthora colocasiae) — DALO: Large irregular dark/brown water-soaked spots on leaves expanding rapidly. The most destructive dalo disease in Fiji. Control: Mancozeb 2.5g/L or Ridomil Gold (Metalaxyl-M + Mancozeb) 2.5g/L.

7. BANANA FRUIT BATS (Pteropus tonganus) — BANANA, PAPAYA: Fiji flying fox. Damage fruit at night. Management: Netting on bunches during maturation. Hunting is restricted under Fiji Wildlife Act.

8. EGGPLANT LACE BUG (Urentius hystricellus): Tiny flat insects on leaf undersides, leaves become pale/silvery. Spray Dimethoate 2mL/L or insecticidal soap.

9. MELON FLY (Bactrocera cucurbitae) — CUCURBITS: Adults puncture developing fruit to lay eggs. Maggots tunnel inside. Use protein bait traps (Cue-Lure). Control infested fruit by bagging and destroying.

10. NEMATODES (Meloidogyne spp.) — ALL CROPS: Root-knot nematodes cause galls/knots on roots, stunting, and yellow plants. No visible pest above ground. Diagnose by digging roots. Control: Crop rotation with non-host crops (cereals, grasses), Tagetes (marigold) cover crop, soil solarization.',
    'PEST_DISEASE',
    NULL,
    'VALIDATED',
    ARRAY['pest-identification', 'fruit-borer', 'diamondback-moth', 'aphids', 'whitefly', 'nematodes', 'Fiji'],
    'en',
    'Teivaka Agronomy Team v1.0',
    1
) ON CONFLICT (kb_entry_id) DO NOTHING;

INSERT INTO shared.kb_articles (kb_entry_id, title, content, category, production_id, rag_status, tags, language, source, version)
VALUES (
    'KB-024',
    'Ferry and Logistics for Island-Based Farms — Kadavu, Ovalau, Taveuni',
    'For Teivaka farms located on outer islands (Kadavu, Ovalau, Taveuni, Lau Group), logistics is not a side consideration — it is a core business constraint that determines crop selection, harvest timing, pricing, and profitability. This article covers practical logistics management for island farming operations.

FERRY SCHEDULES AND CAPACITY:
- Kadavu: Patterson Brothers Shipping operates twice-weekly service Suva–Kadavu (Tuesday and Friday departure from Suva, Wednesday and Saturday return). Cargo deck capacity ~15 tonnes. Perishable freight is loaded last and unloaded first.
- Taveuni: Bligh Water Shipping (Adi Savusavu) operates Suva–Savusavu–Taveuni 3× weekly. Goundar Shipping provides daily Savusavu–Taveuni service.
- Ovalau (Levuka): Consort Shipping operates daily high-speed Suva–Levuka service — best turnaround for time-sensitive produce.

BOOKING FREIGHT: Book cargo 48 hours in advance with the shipping company. For perishable produce, request "deck cargo with tarpaulin cover." Payment is typically cash at Port Berth 1 (Suva) or at the outer island wharf.

CROP SELECTION FOR ISLAND FARMS: On islands with 2× weekly service, avoid highly perishable crops (tomato, lettuce, green beans). Prioritize: kava (completely shelf-stable), cassava (2–3 day shelf life before deterioration), sweet potato (1 week), dalo (3–5 days). Pineapple and banana have sufficient shelf life for 2× weekly ferry.

COLD CHAIN ABSENCE: No refrigerated shipping containers operate on Fiji outer island routes as of 2024. All produce travels ambient. Plan harvest timing: harvest morning of ferry day, boat departs afternoon, arrives Suva next morning, delivered to market by 7am. This means an 18–22 hour journey at ambient temperatures (typically 28–32°C).

PACKAGING FOR TRANSIT: Use sturdy vented plastic crates (rental from Suva vegetable merchants at FJD 2/crate). Never use burlap sacks for soft fruit. Layer banana leaves or dry grass between layers.

COST CALCULATION: Ferry freight for vegetables from Kadavu to Suva is approximately FJD 0.40–0.60/kg plus wharfage fees (~FJD 0.10/kg). For a 200kg shipment, expect FJD 100–140 total freight cost. This must be factored into your pricing model — build it into Teivaka as a delivery cost.

RADIO COMMUNICATION: Many outer island farms rely on HF radio for weather updates and communication with buyers. Teivaka''s offline mode ensures farm data is captured even without internet — syncs when vessel arrives at Suva wharf and farmer connects to WiFi.',
    'CROP_MANAGEMENT',
    NULL,
    'VALIDATED',
    ARRAY['logistics', 'ferry', 'Kadavu', 'Taveuni', 'Ovalau', 'island-farming', 'cold-chain', 'offline'],
    'en',
    'Teivaka Agronomy Team v1.0',
    1
) ON CONFLICT (kb_entry_id) DO NOTHING;

INSERT INTO shared.kb_articles (kb_entry_id, title, content, category, production_id, rag_status, tags, language, source, version)
VALUES (
    'KB-025',
    'Farm Expansion Readiness — When and How to Scale Your Teivaka Operation',
    'Scaling a farm too early is one of the most common causes of farm financial failure in Fiji. Adding land, workers, and infrastructure before the core operation is profitable and systemized simply amplifies problems. This guide defines the Teivaka expansion readiness framework.

EXPANSION READINESS INDICATORS (all five must be met):

1. CONSISTENT POSITIVE CoKG MARGINS: Your last 3 cycles must show CoKG below the crop benchmark price for at least 2 of 3 cycles. If tomato CoKG is FJD 2.10/kg and market price is FJD 2.50/kg, you have a FJD 0.40/kg gross margin. Expansion on thin margins amplifies risk.

2. STABLE MARKET RELATIONSHIPS: You must have confirmed buyers for your expanded output BEFORE expanding production. In Fiji, this means a verbal or written agreement with a hotel, supermarket buyer, or produce merchant. Uncontracted expansion risks flooding the local market and crashing your own selling price.

3. CASH FLOW POSITIVE FOR 6 MONTHS: Teivaka financial reports must show positive net cash flow for 6 consecutive months. This demonstrates operational stability and builds the capital buffer needed for expansion investment.

4. ROTATION PLAN VALIDATED: Your expansion land must have sufficient area to maintain required crop family rotation periods. Expanding onto one paddock and running the same crop continuously will accelerate disease buildup. Run the Teivaka rotation planner on the new area before committing to land lease.

5. LABOR CAPACITY: Calculate labor requirements for expanded area: (area_m² ÷ 10,000) × crop_labor_days_per_hectare. For tomato: 1ha requires 120 labor-days at planting + ongoing harvest labor. Confirm you have reliable worker relationships before committing to expanded area.

PHASED EXPANSION MODEL:
Phase 1 — Demonstrate (Year 1): 0.5–1ha, 1 main crop, master production system
Phase 2 — Replicate (Year 2): 1–2ha, 2 crop types in rotation, document SOPs in Teivaka task manager
Phase 3 — Scale (Year 3+): 3–5ha, multiple production units, dedicated manager, TIS AI supports daily decision-making

ACCESSING CAPITAL: Fiji has several agriculture lending programs: ADB/Government Subsidized Agricultural Credit (8% interest, FJD 50,000 max), Fiji Development Bank Agricultural Loan, HFC Bank Small Farm Loan. Teivaka can export a financial summary report for loan applications — use the Financials → Export CSV function.',
    'FINANCE',
    NULL,
    'VALIDATED',
    ARRAY['expansion', 'scaling', 'readiness', 'finance', 'rotation', 'CoKG', 'Fiji', 'ADB'],
    'en',
    'Teivaka Agronomy Team v1.0',
    1
) ON CONFLICT (kb_entry_id) DO NOTHING;
