/** Covenant — /covenant. The Teivaka Data Ownership Covenant (9 commitments),
 *  rendered from the canonical prototype copy. Linked from the avatar menu + Export. */
import { Link } from "react-router-dom";
import { Shield, ArrowLeft } from "lucide-react";

const C = { soil: "#5C4033", green: "#6AA84F", greenDk: "#3E7B1F", line: "#E8E2D4", cream: "#F8F3E9", muted: "#8A7B6F" };

const COMMITMENTS = [
  ["Ownership", "The farmer owns the data generated by their farm. Whoever founds a tenant owns all records within it — operational, financial, evidence, derived analytics, trust scores. Workers and partners contribute but do not own. Teivaka PTE LTD never claims ownership of any operational farm record, at any time, for any duration."],
  ["Custodianship", "Teivaka is the custodian of farmer-owned data — a service relationship, not an ownership claim. We hold records securely, ensure integrity through hash-chained trails, enable retrieval/export/verification on demand, protect against unauthorized access or loss, and disclose any compromise within 72 hours. Custodianship ends at the farmer's request; ownership always stays with the farmer."],
  ["Aggregation rights — explicit consent required", "Anonymized, aggregated data may inform banks, NGOs, governments and researchers — but only with the farmer's explicit opt-in at signup, revocable anytime in one action. Aggregations enforce a k-anonymity floor of 10, add differential-privacy noise, and never carry tenant, user or farm IDs."],
  ["Right to portability", "Every farmer can export their full data anytime, free, in machine-readable format — every record, evidence artifact, chain entry, derived analytic, and the verification protocol. Exports are portable: take them to another platform, a bank, an auditor, or yourself."],
  ["Right to deletion", "Every farmer can delete their account and data: a 30-day reversible cooling period, WhatsApp/SMS confirmation, and an automatic final export first. Chain entries remain as chain-of-custody with content hashed and unrecoverable. The right isn't contingent on payment, contract, or partnerships."],
  ["Government access — never automatic", "No pre-emptive or standing government access. Access to a specific farmer's records requires the farmer's explicit, time-boxed consent, or a lawful court order served through formal process. Teivaka defends farmer privacy in court when overreach occurs — even when compliance would be commercially convenient."],
  ["Disclosure regime", "An annual transparency report at teivaka.com/transparency: data-access requests by category, grants/refusals, aggregations licensed and to whom, security incidents, audit findings, and covenant changes (with 30-day notice). Reports stay accessible permanently."],
  ["Sovereign data residency", "Where a government requires citizen data to reside in-country, Teivaka stands up regional infrastructure there. A Fijian farmer's data resides in Fiji-aligned infrastructure. This holds even where it costs more — sovereignty is not negotiable."],
  ["Termination protection", "If Teivaka ceases to operate, data does not vanish: a 12-month public sunset, a successor custodian or full export to every tenant, and a verification protocol usable indefinitely without our infrastructure. A successor inherits this covenant in full. Records are never orphaned, sold without consent, or lost to corporate failure."],
];

export default function Covenant() {
  return (
    <div style={{ maxWidth: 820, margin: "0 auto", padding: "4px 0 40px" }}>
      <Link to="/me" style={{ display: "inline-flex", alignItems: "center", gap: 6, color: C.muted, fontSize: 12.5, textDecoration: "none", marginBottom: 12 }}><ArrowLeft size={14} /> Account</Link>
      <div style={{ background: "#fff", border: `1px solid ${C.line}`, borderRadius: 12, padding: "26px 24px" }}>
        <div style={{ fontSize: 11, fontWeight: 700, letterSpacing: ".08em", textTransform: "uppercase", color: C.green }}>Constitutional commitment</div>
        <h1 style={{ display: "flex", alignItems: "center", gap: 10, color: C.soil, margin: "6px 0 8px", fontSize: 26 }}><Shield size={24} style={{ color: C.green }} /> Data Ownership Covenant</h1>
        <p style={{ color: C.muted, fontSize: 14, lineHeight: 1.6, margin: 0 }}>Teivaka PTE LTD's binding commitment to the Pacific farmers whose data flows through this platform. Nine commitments. No carve-outs.</p>
        <div style={{ display: "flex", gap: 18, flexWrap: "wrap", margin: "14px 0 4px", fontSize: 11.5, color: C.muted }}>
          <span><strong>Version</strong> 1.0</span><span><strong>Effective</strong> 2026-05-29</span><span><strong>Status</strong> Locked</span><span><strong>Authority</strong> Uraia Koroi Kama, Founder</span>
        </div>
      </div>

      {COMMITMENTS.map(([title, body], i) => (
        <div key={i} style={{ background: "#fff", border: `1px solid ${C.line}`, borderRadius: 12, padding: "18px 22px", marginTop: 12 }}>
          <div style={{ display: "flex", gap: 12 }}>
            <span style={{ width: 28, height: 28, borderRadius: "50%", background: "rgba(106,168,79,0.14)", color: C.greenDk, fontWeight: 700, fontSize: 13, display: "flex", alignItems: "center", justifyContent: "center", flexShrink: 0 }}>{i + 1}</span>
            <div>
              <h2 style={{ color: C.soil, fontSize: 16, margin: "2px 0 6px" }}>{title}</h2>
              <p style={{ color: C.soil, fontSize: 13.5, lineHeight: 1.65, margin: 0, opacity: 0.92 }}>{body}</p>
            </div>
          </div>
        </div>
      ))}
    </div>
  );
}
